### ISSUE TITLE
Enable creation different types of connection from an element to another

### ISSUE THREAD

**Issue by koppor** [sporritt/jsPlumb#165]
### Context
The context of this request are diagrams, where different type of connectors leave a node. 

### Desired features

* A user should be able to create connections of different types between two nodes via drag'n'drop. The choice of the type is done by a area assigned to the type inside the node.
* It should be programatically possible to create a connection of a certain type between two nodes
* The connections should start and at the border the nodes and not inside them

### Illustration of a possible UI
![illustration](https://f.cloud.github.com/assets/1366654/2050382/5fcb4f2a-8a73-11e3-8e7a-66c95b6fd23f.png)

### Illustration of the use case

    <div class="node" id="node1">node1
      <div class="srcContainer">
          <div class="srcForType1">drag me for type1 conn</div>
          <div class="srcForType1">drag me for type2 conn</div>
      </div>
    </div>

    <div class="node" id="node2">node1
      <div class="srcContainer">
          <div class="srcForType1">drag me for type1 conn</div>
          <div class="srcForType1">drag me for type2 conn</div>
      </div>
    </div>

    <script>
       jsPlumb.registerConnectionTypes({
        "type1": {
          "connector": "Flowchart",
            ...
        },
        "test2": {
          ...
        }
      });
    <script>

Now I want to enable `div.scrForType1` being a source for `type1` connections, which start at it's parent having `.node`. `div.SrcForType2` should be a source for `type2` connections which also start at the respective `.node`.

Additionally, it should be possible to programmatically connect `node1` with `node2` with a connection of `type1` (or `type2`):

    jsPlumb.connect({source: "node1", target: "node2", type: "type1"});

### Current state

Up to version 1.5.4 this was possible using the `parent` property of `makeSource`. In 1.5.5, the contents provided by connect's type are merged together with the type of the first source element created by `makeSource`. Furthermore, the [documentation of connections](http://jsplumbtoolkit.com/doc/connections) says at "Specifying drag source area" that "[Supplying a 'parent' parameter] will probably be discontinued at some stage".

### Issue

A personal discussion with Simon revealed that that usage of jsPlumb was not foreseen by the API. This requests asks for a clean support/API for the described use case.

**Comment by sporritt** [comment]
Elements can now support multiple `makeSource` registrations, both with the mouse and programmatically. So I'm closing this out. 

This from the original description:

> The connections should start and at the border the nodes and not inside them

is not done; it's a separate issue from the other two items. it may even be the case that you can already do this.
