### ISSUE TITLE
Cannot create an endpoint if the ID contains :

### ISSUE THREAD

**Issue by computamike** [sporritt/jsPlumb#192]
Summary : 
I am using Jquery to retrieve elements from the page, which I am going to pass into JsPlumb to create anchor points.

The page elements on the page containg : in the id cause a problem within the JSplumb library.

I have developed a small page to demonstrate this issue.  I'm not sure how to attach this evidence, so pasting the HTML code here - if this isn't protocol I apologise.

<!doctype html>
  <html>
    <head>
        <title>jsPlumb simple example</title>
        <style type="text/css">
            .w { 
                border:1px solid #456;
                position:absolute;
                width:60px;
                height:60px;
                z-index:10;
             }

             ._jsPlumb_connector { 
                 z-index:9;
             }

             #one { 
                 left:50px;
                 top:50px;
             }

             #two{
                 left:350px;
                 top:350px;
             }
        </style>
    </head>
    <body>
        <div id="one"	class="one">one</div>
        <div id="two"	class = "two(works)">two</div>
        <div id="two:0"	class = "two">two</div>
        Drag a connection from <strong>one</strong> to <strong>two</strong>
        <div id="debug"></div>

        <script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js'></script>
        <script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min.js'></script>
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jsPlumb/1.4.1/jquery.jsPlumb-1.4.1-all.js"></script>

        <script type="text/javascript">

$(document).ready(function() {
    $('div[id="one"]').each(function() {
       //alert($(this).text());
    }); 

            jsPlumb.ready(function() {
                jsPlumb.addEndpoint($('div#one'), { isSource:true });
                jsPlumb.addEndpoint($('div#two'), { isTarget:true });
                jsPlumb.addEndpoint($('div#two\\:0'), { isTarget:true });

                jsPlumb.bind("connection", function(info) {
                    console.log("new connection:", info);
                    $("#debug").html("hello.");
                });
            });

});
        </script>
    </body>
</html>

**Comment by sporritt** [comment]
i've verified that in jsplumb 1.7.5 you can connect elements whose IDs contain characters such as colons (in both jQuery and Vanilla flavours).  This is presumably due to the removal of the `getElementObject` function.  closing this out.
