### ISSUE TITLE
Perimeter Anchor with Rotation

### ISSUE THREAD

**Issue by radlws** [sporritt/jsPlumb#213]
I noticed that using rotation increments of 90 degrees works well. Trying other combinations, such as 45 degrees creates a much larger perimeter anchor around the image. To test this out, refer to the official perimeter anchor demo and use add the following css:

```
._45[data-shape=Square] {
    width:150px;
    height:150px;
    left:570px;
    top:160px;
    line-height: 150px;
    background-image:url(diamond.png); /* 45 degree square, same as diamond */
    /*border: 1px solid black;*/
}
```
and the following html:

```
<div class="shape _45" data-shape="Square" data-rotation="45">Square 45</div>
```
Now inspect the perimeter around the shape.

**Comment by sporritt** [comment]
yes, true. it doesnt use CSS3 to make the shapes, so there is always the concept of a bounding rectangle.

**Comment by chj-damon** [comment]
@sporritt How can I draw svg shapes in jsPlumb? any hints for me?

**Comment by sporritt** [comment]
@chj-damon jsPlumb is not really designed as a tool to draw svg shapes, but there are some basic methods that can be used, it's all quite low level though.

try this in the console, for example:

```
var s = jsPlumbUtil.svg.node("svg", { width:500, height:500, style:"position:fixed;z-index:100000;left:0;top:0;background-color:white" });
var c = jsPlumbUtil.svg.node("circle", { r:50,cx:250,cy:250, "stroke-width":3, stroke:"blue", fill:"none" });
s.appendChild(c);
document.body.appendChild(s);
```

you'll get this:

![image](https://user-images.githubusercontent.com/262720/27380008-e09e0706-56c0-11e7-80c6-7409d9f78380.png)

**Comment by chj-damon** [comment]
@sporritt Thank you so much. It really helps me out.
