### ISSUE TITLE
scroll is ignored in offset calculations

### ISSUE THREAD

**Issue by sporritt** [sporritt/jsPlumb#237]
examples:

http://jsfiddle.net/BQWL4/
http://jsfiddle.net/ZUm7p/58/

note 1.3.16 could take scroll into account:

http://jsfiddle.net/sporritt/ZUm7p/50/

The question is, what to do about this? checking the scroll values of all intermediate elements between a plumbed element and the container is not very appealing. can getBoundingClientRect help?

**Comment by bourcha** [comment]
I have the same problem as <b>RAHILKHERA</b>. In this <a href="http://jsfiddle.net/ZUm7p/58/">http://jsfiddle.net/ZUm7p/58/</a> I changed the jsPlumb version to dom.jsPlumb-1.7.2-min.js, I connected, for example, <i>Number</i> to <i>Price</i> and when I scroll in the <i>SalesOrderLine</i> table the connection does not "follow" the <i>Price</i> element's position but remains fixed. As a result when I scroll the <i>Number</i> no longer points to <i>Price</i> but to <i>Discount</i>.

What really surprises me is that the above bug isn't present in this <a href="http://jsfiddle.net/sporritt/ZUm7p/50/">http://jsfiddle.net/sporritt/ZUm7p/50/</a>. Have you fixed it recently? Do I need to download something that will solve the problem till the next release? 

I know you are on it, I'm simply posting this because in your last comment it seamed as if you are asking to see how many people would like to see it fixed so you can prioritize.

**Comment by sporritt** [comment]
That one uses jsplumb 1.3.16:  

![image](https://cloud.githubusercontent.com/assets/262720/5660059/b974bfe8-976f-11e4-928a-ee38f71b5391.png)

Thanks for the upvote.  i'd like to find some time to get this done, but i've been kind of busy recently. i'm still not sure whether this would be best done automatically (implying a bit of a performance hit for all usages of jsplumb, not ideal) or as a specific "i am connecting two lists" type of use case. Any preference?

**Comment by bourcha** [comment]
I've updated the jsplumb version from 1.3.16 to 1.7.2. It will form a connection only between <i>OrderDate</i> and any other element in the <i>SalesOrderLine</i> but for those connections it works properly.

In the project I'm working right now a specific "i am connecting two lists" type won't be very helpful. There is a "middle div" between my two lists. For example <i>Number</i> and <i>OrderDate</i> might end up in a "middle div" that will concatenate the two and assign in as a <i>SalesOrderNumber</i> in the <i>SalesOrderLine</i> list. My implementation of jsplumb doesn't interest you really but my point is that the scroll might not always affect just the two lists.

**Comment by mkaranasou** [comment]
Hi,
The same thing has been troubling me too (what is seen here http://jsfiddle.net/ZUm7p/58/ with 1.7.2 version) and I can't seem to be able to work around it (e.g. with repaint or repaint everything giving specific left/top). In my case it is not exactly a direct connection of two lists, so, It's not clear to me if "i am connecting two lists" type of solution would cover this case. Could you, please, give an example? Do you mean to have this as an optional feature (with the use of a flag for example) and those who use it will be aware that performance may be a bit compromised? 

Thanks a lot for your time and help!

**Comment by sporritt** [comment]
@bourcha  i am **always** interested in people's use cases for jsPlumb.  It's how I decide what features to add and how they should work.

it sounds like, from your comments and from what @mkaranasou said, a specific "connecting two lists" feature would not be all that useful. 

The key problem when adjusting connections to take into account their position with regards to the scroll of their parent, is that ...well, there are two.  First, yes there's more maths required because i'd have to go up through the DOM adjusting positions as I go along; at the moment I don't have to bother with that at all and can just look at the `offsetLeft` and `offsetTop` properties. Maybe that maths would cause jsPlumb to be slower; I don't know. If it did - and it was significant - then I suppose it would be possible to put it on a flag. But what I was also going to say is that if you've got connections whose endpoints may not actually be visible any longer due to their parent element's scroll, what do you do?

in the fiddle you guys are linking to i setup a scheme that saw the connection jump to the parent's top left corner as soon as it had been scrolled out of view:

![image](https://cloud.githubusercontent.com/assets/262720/5660506/30771a32-9775-11e4-912c-fc8ca1138e8a.png)

and so that's what i was referring to when i mentioned the "connecting two lists" use case.  it is also possible that the desired behaviour would be just to hide the connection. 

as i said, i'm always interested in suggestions from people.  one of the reasons i haven't really moved on this yet is the absence of any definitive suggestion or requirement from someone.

**Comment by bourcha** [comment]
Well I guess everything depends on people's implementation but when I started my project I was using version 1.4 of jsPlumb and when the browser loaded I wanted all my list's elements collapsed and all of my connections hidden and as the list expanded I had a "visibleAndonScreen" function fire ,which basically implemented the jQuery <code>:visible</code> Selector and something like <a href="http://upshots.org/javascript/jquery-test-if-element-is-in-viewport-visible-on-screen">this</a> (which checked whether an element was visible on screen), for each element with a connection. 

Same with scrolling I did something like this:
<img src="http://s2.postimg.org/duva77wih/sample_code.png" alt="sample-code">
My problem is that after switching to the new version <code>jsPlumb.repaintEverything();</code> doesn't seam to do the trick.

**Comment by sporritt** [comment]
fixed in 1.7.4..one example:

http://jsfiddle.net/BQWL4/7/

note that if you're looking at this issue in The Future the fiddles will no longer work as they'll be linking to an old version of jsplumb.

**Comment by fgi-github** [comment]
Hi,
It looks like it reappeared in latest 2.0.7. I'm having the same problem on all browsers but Firefox (where everything is displayed correctly). Here's an example of some code that is not correctly working http://stackoverflow.com/questions/35806461/jsplumb-repainteverything-not-working-on-every-browsers-but-firefox

**Comment by sporritt** [comment]
but it was the container?

![image](https://cloud.githubusercontent.com/assets/262720/13554056/e5606bf0-e3f1-11e5-8cfe-d82cc01bd919.png)

**Comment by fgi-github** [comment]
Yes, because connectors are not expressed on elements at the same dom level, I had to set the container, but I wrongfully followed an advice to put the body element. I replaced by the actual top level div containing the content. I had to test and try to find the right container.
