### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by kentcdodds** [sporritt/jsPlumb#275]
Could you please [publish this to npm](https://gist.github.com/coolaj86/1318304)?

**Comment by Jon-Biz** [comment]
:+1: I'm currently using jsplumb in an atomify project, and so having it npm/browserify compatible would be much more convenient.

**Comment by sporritt** [comment]
i've thought about this some more. I'm not going to do this.  I would welcome someone from the community managing a downstream that handled this.

**Comment by Jon-Biz** [comment]
Challenge accepted :)

**Comment by sporritt** [comment]
alright cool.
