### ISSUE TITLE
How to catch jsplumb draggable event ?

### ISSUE THREAD

**Issue by absar-mushtaq** [sporritt/jsPlumb#309]
I want to save positions after dragging of element. You can acheive it using jquery-ui draggable BUT it somehows disrupts making connections, instead of making connection it starts dragging. So how do i catch drag event from jsPlumb?

**Comment by euschen** [comment]
Just use the dragOptions object when you define an Endpoint: 
http://www.jsplumb.org/doc/connections.html#dragOptions

you can define jquery-ui properties there like so: 
...
dragOptions: {
   drag: function(event, ui){...},
   start: function(event, ui){...}
}
