### ISSUE TITLE
setContainer does not work when container has overflow: scroll;

### ISSUE THREAD

**Issue by hannupekka** [sporritt/jsPlumb#313]
See fiddle for example: http://jsfiddle.net/ucp9L2s2/8/

When scrolling table to right, endpoints won't follow with scrolling. Is this how it should work or is there something wrong with it? :)

**Comment by sporritt** [comment]
i wonder if this is related to issue #312 


what would you expect it to do if you scrolled the "right" table to the point that one of the endpoints was about to slip underneath the "left" table?

**Comment by hannupekka** [comment]
Heh, that's a good question, actually. Here's a "working" fiddle with jsPlumb 1.4.1: http://jsfiddle.net/ucp9L2s2/9/ - repaintEverything() is required on scroll event.

It seems that with 1.7.2 it is the "setContainer" that breaks it with overflowing elements. Also repaintEverything() does nothing with it.

**Comment by sporritt** [comment]
yes that question - or rather the absence of an answer to it from anyone - is the main reason this is still outstanding. i think the intuitive answer is that the connections should be either hidden or transferred to some "holding" element when their endpoints are no longer visible.  but how to do that via the api, i'm not entirely sure.

that fiddle you linked to doesn't "work" as far as i can see - the endpoints don't move, sure, but neither do they track the right table.

**Comment by hannupekka** [comment]
In our use case, our tables have higher z-index than the connecting lines so connections just slide under the left table.

**Comment by sporritt** [comment]
![image](https://cloud.githubusercontent.com/assets/262720/5833597/09a7fb0e-a1a9-11e4-8c81-3bf22787d059.png)


like that? and you're happy for it to be like that?

**Comment by sporritt** [comment]
(i dont know why that fiddle didnt do this for me before)

**Comment by hannupekka** [comment]
Well, yeah, it that is fine in our case. Both tables have higher z-index than connectors which then would be just hidden behind, when scrolled all the way to right.

**Comment by sporritt** [comment]
ok. this is different from one of the other use cases - a more common one perhaps - in which the user is connecting two lists of items. your issue could be fixed simply be taking the scroll into account when calculating the offset. i'll see what i can do, maybe i can get it into 1.7.3.

**Comment by hannupekka** [comment]
Thanks for your support with this! And for jsPlumb! :+1:

**Comment by sporritt** [comment]
@hannupekka I've made a couple of small updates to the offset calculation function, on the 1.7.3 dev branch.  you can see a fiddle that uses it here (hosted on my test site)

http://jsfiddle.net/ucp9L2s2/36/

so, it seems to work.  changes like this, though, being quite fundamental, are the sorts of things i'm very cautious about releasing, so right now i can't give you an ironclad guarantee that this will end up getting released!  it does seem quite likely that it will, given that you're not the first person to ask about this, and also the change is "new" code: it doesn't alter the behaviour in any situation for which the code is currently known to work. but you never know.  maybe something will come out of left field and scupper the whole thing.

**Comment by hannupekka** [comment]
Great, thanks!

**Comment by sporritt** [comment]
calling this done.  the work in 1.7.3 dev is going to be released.
