### ISSUE TITLE
Connections are not working on Chrome

### ISSUE THREAD

**Issue by mohtashimjamal** [sporritt/jsPlumb#316]
Hello There,

I am facing an issue that the connection between two objects did not working on Chrome version 36.0.1985.125 and the same is working fine in Firefox.

Please suggest any solution for the same.

Thanks in advanced.
Mohtashim J

**Comment by sporritt** [comment]
you need to provide a jsfiddle or something. there is no actionable information in this issue report.

**Comment by mohtashimjamal** [comment]
My issue was resolved. Thank you

**Comment by sporritt** [comment]
!
