### ISSUE TITLE
Docs incorrectly refer to "mouseenter"

### ISSUE THREAD

**Issue by rmadsen** [sporritt/jsPlumb#317]
I was extremely confused why my event handler on a connection was not firing on "mouseenter" but had no problems with "click." Finally I went to the source where I saw:

```js
		//events = [ "click", "dblclick", "mouseenter", "mouseout", "mousemove", "mousedown", "mouseup", "contextmenu" ],
        events = [ "click", "dblclick", "mouseover", "mouseout", "mousemove", "mousedown", "mouseup", "contextmenu" ],
		eventFilters = { "mouseout":"mouseleave", "mouseexit":"mouseleave" },
```
I'm not sure when it switched to the new event names (mouseenter -> mouseover), but please update the docs to reflect the change!

Thanks for the great library.

**Comment by sporritt** [comment]
i need to look a little more closely at this i think.  i want to support both `mouseover` and `mouseenter`, really: they are distinct concepts, and both jQuery and Mottle (the event library vanilla jsPlumb uses) support binding to `mouseenter` (and, for that matter, `mouseleave`).

jQuery's docs explain the distinction:

http://api.jquery.com/mouseenter/

**Comment by sporritt** [comment]
..for now i am updating the docs.  looking at `mouseenter` and `mouseexit` in a future release. closing this out; the docs are updated and will be pushed when 1.7.3 is released shortly.
