### ISSUE TITLE
Elements go out of the container on screen resize

### ISSUE THREAD

**Issue by rohanmjoshi** [sporritt/jsPlumb#319]
Currently if you are have a limited drawing area (container) and you are on a higher resolution screen, when you move to a lesser resolution/smaller screen, the jsPlumb elements tend to go out of the container. You can drag them back into the container, but jsPlumb needs to handle this. The problem is occurring because all the jsPlumb elements need to have absolute positioning.

I have attached images to explain what I mean.

There should also be a functionality in the jsPlumb API in which you "format" the flowchart. All the elements are arranged by their levels in a neat manner.

HIgh resolution screen
![hr](https://cloud.githubusercontent.com/assets/2755791/6132984/9165fdfe-b10b-11e4-9507-4f9725b87119.png)

After dragging to low resolution screen
![lr](https://cloud.githubusercontent.com/assets/2755791/6132986/948a3b80-b10b-11e4-8118-23fa7c3e2d46.png)

**Comment by sporritt** [comment]
not a jsplumb issue. you need to set `overflow:hidden`, or whatever you want, on your container.
