### ISSUE TITLE
Bower integration

### ISSUE THREAD

**Issue by andytango** [sporritt/jsPlumb#320]
I'd recommend adding

  "main":[
	"/dist/js/dom.jsPlumb-1.7.2-min.js"
  ]

to bower.json file so bower injects this into the html on yeoman/bower frameworks. Could add bower steps to readme also.

**Comment by patbaker82** [comment]
I think this might be a bit better as isn't specific to a version

```
  "overrides": {
    "jsplumb": {
      "main": "dist/js/dom.jsPlumb-!(*-min)*.js"
    }
  }
```

**Comment by sporritt** [comment]
currently it looks like this

```
"main": [
    "dist/js/dom.jsPlumb-1.7.5.js"
  ]
```

i think there's been a `main` entry for quite some time.
