### ISSUE TITLE
Incorrect documentation for adding connector type in addEndpoint()

### ISSUE THREAD

**Issue by rohanmjoshi** [sporritt/jsPlumb#322]
The webpage here : http://www.jsplumb.org/doc/types.html#connection-type, 

says that if I were to add a connector type via the addEndpoint call, I would have to set the connectorType parameter. This is wrong. It does not work. What you need to set is the connectionType parameter.

The webpage needs to be corrected.

**Comment by sporritt** [comment]
fixed in dev
