### ISSUE TITLE
Custom attributes in connections svg html element

### ISSUE THREAD

**Issue by davideferre** [sporritt/jsPlumb#323]
This is an enhancement, not an issue. It would be nice if connection element can get custom html attributes from connect method. I would pass to svg element some infos that can be useful when user click on a connection.

Alternatively from connection object it can be useful to get anchor element interested in this connection (at the moment I can get endpoints only).

**Comment by davideferre** [comment]
I've not found *parameters* param on *connect* method, sorry. [This is the link to the doc](http://www.jsplumb.org/doc/parameters.html).

**Comment by sporritt** [comment]
thanks for updating, and the link to the docs.

**Comment by dlinx** [comment]
Cant set custom attribute which can be used for styling of link, I am using jsplumb with angularjs, and I want to use ng-class with jsplumb link

**Comment by sporritt** [comment]
@dlinx you can use `class` though, with the `cssClass` property.

**Comment by dlinx** [comment]
If it is class, then I cant change it conditionally, I am going to use  ng-class="classname:someCondition"

**Comment by sporritt** [comment]
@dlinx So you would like the ability to provide a list of attributes that you want set on the resulting elements?

**Comment by viswesh** [comment]
@sporritt I would like this feature as well. 

Something like,
```
jsPlumb.connect({
  source:"element1", 
  target:"element2",
  attributes: {
     data-type: "xxx"
  }
});
```

The resulting elements (SVG/Path) will have data-type as a custom attribute. 

```
<svg style="position:absolute;left:490.1339745962156px;top:76.99038105676658px" width="109.73205080756884" height="236.01923788646684" pointer-events="none" position="absolute" version="1.1" xmlns="http://www.w3.org/2000/svg" class="jtk-connector link" data-type="xxx">
```

```cssClass``` can also be used but it will be nice to set custom attributes. This way, css is not tied with anything data.
