### ISSUE TITLE
Can't drag cloned divs (.clone(true,true))

### ISSUE THREAD

**Issue by LucasRe** [sporritt/jsPlumb#324]
I explain here http://stackoverflow.com/questions/28570730/javascript-clone-doesnt-work

Basically when I use .clone (true, true), jsPlumb.draggable () does not work on this object, does not add 'ui-draggable'.

**Comment by sporritt** [comment]
that really is a lot of code, as the first person commented.

if you clone the node then it has the `ui-draggable` class already probably, and jsPlumb will not re-initialise an element that it already considers to be draggable.

in the future please ask these sorts of question in the groups.  this is not an issue with jsplumb.

**Comment by LucasRe** [comment]
For example, when I use box = obj.clone(), jsPlumb.draggable (box), the jsplumb add the 'ui-draggable' and i can drag the object
But, when I use I use box = obj.clone(true,true), jsPlumb.draggable (box), the jsplumb do nothing.
The jsPlumb dosent add the 'ui-draggable', it is the same code, just change .clone() for .clone(true,true)
So I tinhk it is a jsplumb bug.

**Comment by sporritt** [comment]
i dont think it is. please provide a working jsfiddle in which the fact that it is a bug is demonstrated. in the meantime i am closing this issue.

**Comment by sporritt** [comment]
....and the reason i don't think it is, in case you missed it above, which i think you might have: assuming this `clone` method you're talking about works like `cloneNode` in the DOM, then it has a "shallow" version, which takes no arguments, and a "deep" version, which takes arguments. The deep version copies _everything_, including the classes on the element.

jsPlumb, when deciding whether or not to make something draggable, looks for the `ui-draggable` class on an element, and if it is present it does not re-initialise the dragging (that's in the jQuery flavour which it looks like you are using).  So after a deep clone it has the class that causes jsPlumb to do nothing.  You could try removing that class after the deep clone.

**Comment by LucasRe** [comment]
I removed, that is the problem

"var block = $(selected).clone(); //clone selected block
block.css({ left: mouse.X+'px', top: mouse.Y+'px'}).attr('id', idn ).removeClass('ui-draggable selected'); // remove the ui-draggable and selected class"

then, if I call 

"block.appendTo($(container)); // Append block to container
jsPlumb.draggable(block, dragop);// dragop = drag options"

i can drag the block

But, when i put

"var block = $(selected).clone(true,true); //deep clone of selected block
block.css({ left: mouse.X+'px', top: mouse.Y+'px'}).attr('id', idn ).removeClass('ui-draggable selected'); // remove the ui-draggable and selected class
block.appendTo($(container)); // Append block to container
jsPlumb.draggable(block, dragop);// dragop = drag options"

I cant drag, the jsPlumb.draggable dosent add the ui-draggable class like in the first case

**Comment by sporritt** [comment]
i can't help you without a jsfiddle. i know this is not a jsplumb issue though.

**Comment by LucasRe** [comment]
Np, I will make a jsfiddle as soon as possible :)

**Comment by sporritt** [comment]
if you like. and if you really feel like this is a jsplumb issue. i really don't. i think i mentioned that ...
