### ISSUE TITLE
Cannot drag on touchscreen monitors

### ISSUE THREAD

**Issue by slandmann** [sporritt/jsPlumb#325]
Hi,

I cannot drag using the mouse on laptop with a touchscreen. This occurs in my project as well as the jsplumb demo. Is there a fix for this?

**Comment by sporritt** [comment]
@slandmann is this on jquery or vanilla jsplumb?

**Comment by slandmann** [comment]
It seems to be an issue on vanilla jsplumb as I can drag around using jquery's draggable example without any issues on the same system. Any ideas? Thanks in advance.

**Comment by sporritt** [comment]
without a jsfiddle and some more information about hardware, no.

**Comment by sporritt** [comment]
adding to 1.7.4 milestone just for tracking...without more information i can't do anything about this right now.

**Comment by sporritt** [comment]
closing this because there are no details.  seems possible it is a duplicate of #295.

**Comment by sporritt** [comment]
..and 295 is fixed in 1.7.5 dev, so this likely is too.
