### ISSUE TITLE
Connect all windows in sourcesAndTargets layout

### ISSUE THREAD

**Issue by vanja86** [sporritt/jsPlumb#327]
Hello, everyone. I've created a loop in PHP that generates target windows based on result in mysql database, so I'm wondering is there a simple way to make all of that windows to the source one?

From what I've seen there is line that create's connection and goes like: 

instance.connect({ source:"sourceWindow1", target:"targetWindow5" });.

but that only connect target window5. My target windows are like targetWindow[$i] based on a for loop.

So how to make it connect's all of my generated targetWindows instead defining connections inline like i posted in that example above. Thanks in advance for answer, Best regards!

**Comment by sporritt** [comment]
you posted this question to the groups, which is the suggested course of action, because this is just a question. it is not an issue and does not belong in the issue tracker at all. please refrain from posting questions to the issue tracker.
