### ISSUE TITLE
endpoint label not working in 1.7.3?

### ISSUE THREAD

**Issue by koosvanderkolk** [sporritt/jsPlumb#332]
Am I right that its not longer possible to provide endpoint labels (e.g. text) in the latest version of jsplumb?

I just updated my jsplumb to 1.7.3 and the labels are gone. Downgrading to 1.7.2 makes them appear again.

**Comment by sporritt** [comment]
Can you post a snippet of your config? That's definitely not by design.

**Comment by alrh** [comment]
This is an example of a config we used:

```javascript
{
	"endpoint": "Rectangle",
	"anchor": [0.5, -0.07, 0, -1],
	"paintStyle": {
	  "width": 40,
	  "height": 15
	},
	"isSource": true,
	"isTarget": false,
	"connectorClass": "kw_connection",
	"cssClass": "kw_port kw_port_out",
	"maxConnections": -1
	"overlays": [["Label", {"label": "Label text", "cssClass": 'kw_port_label', "id": "66"}]],
	"connectorOverlays": [["Arrow", {"width": 10, "length": 10, "location": 1, "id": ""}]],
	"connector": ["Flowchart", {"stub": [10, 10], "gap": 10, "cornerRadius": 5, "alwaysRespectStubs": true}],
	"connectorStyle": {
	  "lineWidth": 4,
	  "strokeStyle": "#444"
	},
	"connectorHoverStyle": {
	  "lineWidth": 4,
	  "strokeStyle": "#ccc"
	}
}
```

This works with 1.7.2 (using `jsPlumb.addEndpoint(...)`), but with 1.7.3 the label is not created.

**Comment by Eugenitals** [comment]
In my case
```
(function (endpoint, el) {
                el.addEventListener('mouseover', function () {
                    if (!endpoint.getOverlay('label')) {
                        endpoint.addOverlay(["Label", {
                            label: endpoint.endpointModel.getHint(),
                            location: endpoint.endpointModel.getLocationParams(),
                            cssClass: cssLabelClass
                        }, {id: 'label'}]);
                    }
                });
                el.addEventListener('mouseout', function () {
                    endpoint.removeOverlay('label');
                });
            })(jspEndpoint, jspEndpoint.canvas);
```
It also works with 1.7.2, but not with 1.7.3

**Comment by sporritt** [comment]
exactly what bit of that does not work,  @Eugenitals ?

**Comment by sporritt** [comment]
@alrh in fact you can see this on the jsplumb demo...i hadnt noticed:

http://jsplumb.org/demo/flowchart/dom.html

there used to be 'Drag' and 'Drop' labels.

oddly, the unit test that tests supplying overlays to an endpoint does not report any issue.

**Comment by Eugenitals** [comment]
Actualy, method *addOverlay* to  does not add **<div class="_jsPlumb_overlay">...</div>**.
When I quickly looked into the source code, i`ve found that  in [dom.jsPlumb-1.7.3.js:6716](https://github.com/sporritt/jsPlumb/blob/master/dist/js/dom.jsPlumb-1.7.3.js#L6716) this._jsPlumb.overlays is not Array and has not *length* attribute, so overlays would not be painted

**Comment by sporritt** [comment]
yes that is the issue. just fixed it in 1.7.4 dev. i'm about to push.

**Comment by sporritt** [comment]
ok fixed

**Comment by sporritt** [comment]
(in the 1.7.4 branch)

**Comment by alrh** [comment]
Thanks for the quick response!

**Comment by koosvanderkolk** [comment]
Thanks!
