### ISSUE TITLE
ReattachConnections not working when a connection is detached (jquery & vanilla 1.7.3)

### ISSUE THREAD

**Issue by e-lefort** [sporritt/jsPlumb#333]
While ReattachConnections is set to true, an existant connection dragged/dropped with no source or destination is automatically deleted.

The same code worked perfectly on jquery 1.7.2

**Comment by sporritt** [comment]
this is fixed in 1.7.4 dev

**Comment by e-lefort** [comment]
Thanks !

**Comment by sporritt** [comment]
no problem.  i released 1.7.4 yesterday but havent yet announced it.
