### ISSUE TITLE
Incorrect file names in dist/js/* in "1.7.4" branch

### ISSUE THREAD

**Issue by Eugenitals** [sporritt/jsPlumb#335]
Hello!

In "1.7.4" branch, file **bower.json** contains
```
"main": [
    "dist/js/dom.jsPlumb-1.7.4.js",
    "dist/js/jquery.jsPlumb-1.7.4.js"
  ]
```
but files in directory marked as *-1.7.3.js

**Comment by Eugenitals** [comment]
Looks like *dist/js/* contains previous 1.7.3 version is it correct behavior?

**Comment by sporritt** [comment]
there are both in there right now.  1.7.4 is not yet released. just ignore the 1.7.3 ones.

**Comment by carloschneider** [comment]
+1
