### ISSUE TITLE
JsPlumb (div).clone() Issue

### ISSUE THREAD

**Issue by LucasRe** [sporritt/jsPlumb#337]
Look this jsfiddle
https://jsfiddle.net/3o38nbzs/4/ when I clone, I can move the clone, but it does not "listen" click.
https://jsfiddle.net/L5mg87jm/ when I clone, the clone is static.

At first I used Clone () and the second clone (true, true), that is the only difference.

How do I create a clone to respond to the click event?

**Comment by sporritt** [comment]
isnt this something you asked about in the groups recently?

**Comment by sporritt** [comment]
..no..it was actually [on Github](https://github.com/sporritt/jsPlumb/issues/324).

we've covered this in some detail. please do not open new issues for something we've already discussed.

**Comment by LucasRe** [comment]
Ok, sorry, I still do not know how the github's system issues works. :(
But you saw what's going on?
