### ISSUE TITLE
Dragging position issue if container is set

### ISSUE THREAD

**Issue by dlinx** [sporritt/jsPlumb#338]
set container for jsPlumb to a div whose left and top position is not 0, add a element inside it, and set it as draggable, while dragging that element, the mouse and element has a big difference of position.

**Comment by sporritt** [comment]
Please provide a jsfiddle.

**Comment by dlinx** [comment]
Resolved issue by setting relative position to container.

**Comment by sporritt** [comment]
sometimes i wonder if jsPlumb should do this when a container is set.  but i don't like to be intrusive, generally speaking.
