### ISSUE TITLE
Issue in configuring outline color by using CSS in jsPlumb

### ISSUE THREAD

**Issue by PoundrikM** [sporritt/jsPlumb#339]
Hello Team
I am facing some trouble to get outline color while establishing connection between two end points.
I am using CSS for configuring color of connection by using css style svg.my-connector path {stroke: green;} and applying class my-connector to connectorClass like  connectorClass : "my-connector". 

In this case outline and connector both taking same color.

any best approach so that i can configure outline color through CSS.

**Comment by sporritt** [comment]
`outlineColor` is done via JS, not in CSS. It's documented on this page:

http://jsplumb.org/doc/paint-styles.html
