### ISSUE TITLE
Please extend connection object with sourceUUID and targetUUID property

### ISSUE THREAD

**Issue by tmmls** [sporritt/jsPlumb#344]
Hi,

With this post I would like to submit a feature request.

Currently when using connection objects, given by the jsPlumb.getConnections() methode, the connection object doesn't contain any information of the start endpoint UUID and receiving endpoint UUID. It would be very usefull if the object could contain a sourceUUID and targetUUID property.

This would be very usefull in rebuilding the connection using the UUIDs like ...
jsPlumb.connect({ uuids:[connection.sourceUUID,connection.targetUUID] });

Thanx and keep up the good work ...

**Comment by tmmls** [comment]
Maybe the easiest and best way to implement this feature, is to extend the endpoint class with an getUUID propertie/methode....

**Comment by sporritt** [comment]
@tmmls i think i will do this as a `getUuids` method on Connection, returning an array. Then there is no impedance mismatch with the way you'd recreate a connection with the uuids.  

and also of course i'll put the uuids in the output of `getConnections`

**Comment by sporritt** [comment]
this is done in 1.7.5 dev now
