### ISSUE TITLE
Error when two linked objects are with exactly same position.

### ISSUE THREAD

**Issue by dlinx** [sporritt/jsPlumb#345]
When you drag and move two objects to exactly same position, it throws two errors as 

Error: Invalid value for <svg> attribute width="NaN" 
Error: Invalid value for <svg> attribute height="NaN" 

There might be problem with calculation of height and width.

**Comment by sporritt** [comment]
this is in chrome? in the console?  but the app still runs?

what version of jsPlumb?

**Comment by dlinx** [comment]
Browsers: Google Chrome (38.0.2125.104), Mozila Firefox 31.0

jsPlumb Version: 1.7.3

**Comment by sporritt** [comment]
fixed in 1.7.5 dev
