### ISSUE TITLE
version 2.0

### ISSUE THREAD

**Issue by navinSing** [sporritt/jsPlumb#346]
when can we expect version 2.0 on svg ?

Thanks

**Comment by sporritt** [comment]
I don't really know what you mean...jsPlumb already uses svg in supported browsers.

**Comment by navinSing** [comment]
Weird ... my browser supports SVG ... still it was showing div and htmls
was checking this url :
https://jsplumbtoolkit.com/demo/flowchart/jquery.html

**Comment by sporritt** [comment]
What browser is this? On which OS?

**Comment by navinSing** [comment]
chrome and ubuntu

i have also checked on windows 8 and latest version of chrome..

Still div and Html

Below is some sample generated code(taken from inspect element) :

<div class="demo flowchart-demo" id="flowchart-demo">
                <div class="window _jsPlumb_endpoint_anchor
jsplumb-draggable _jsPlumb_connected"
id="flowchartWindow1"><strong>1</strong><br><br></div>
                <div class="window _jsPlumb_endpoint_anchor
jsplumb-draggable _jsPlumb_connected"
id="flowchartWindow2"><strong>2</strong><br><br></div>
                <div class="window _jsPlumb_endpoint_anchor
jsplumb-draggable _jsPlumb_connected"
id="flowchartWindow3"><strong>3</strong><br><br></div>
                <div class="window _jsPlumb_endpoint_anchor
jsplumb-draggable _jsPlumb_connected"
id="flowchartWindow4"><strong>4</strong><br><br></div>
            <div class="_jsPlumb_endpoint _jsPlumb_endpoint_anchor
jsplumb-draggable jsplumb-droppable _jsPlumb_endpoint_connected
_jsPlumb_endpoint_full" style="position: absolute; height: 20px; width:
20px; left: 291px; top: 255px;"><svg
style="position:absolute;left:0px;top:0px" width="20" height="20"
pointer-events="all" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml"><circle cx="10" cy="10" r="7" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="transparent" stroke="#7AB02C"
style="" stroke-width="3"></circle></svg></div><div
class="_jsPlumb_endpoint _jsPlumb_endpoint_anchor jsplumb-draggable
jsplumb-droppable _jsPlumb_endpoint_connected _jsPlumb_endpoint_full"
style="position: absolute; height: 20px; width: 20px; left: 291px; top:
350px;"><svg style="position:absolute;left:0px;top:0px" width="20"
height="20" pointer-events="all" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml"><circle cx="10" cy="10" r="7" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="transparent" stroke="#7AB02C"
style="" stroke-width="3"></circle></svg></div><div
class="_jsPlumb_endpoint _jsPlumb_endpoint_anchor jsplumb-draggable
jsplumb-droppable _jsPlumb_endpoint_connected" style="position: absolute;
height: 22px; width: 22px; left: 242px; top: 301.5px;"><svg
style="position:absolute;left:0px;top:0px" width="22" height="22"
pointer-events="all" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml"><circle cx="11" cy="11" r="11" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="#7AB02C" stroke="none"
style=""></circle></svg></div><div class="_jsPlumb_endpoint
_jsPlumb_endpoint_anchor jsplumb-draggable jsplumb-droppable
_jsPlumb_endpoint_connected" style="position: absolute; height: 22px;
width: 22px; left: 338px; top: 301.5px;"><svg
style="position:absolute;left:0px;top:0px" width="22" height="22"
pointer-events="all" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml"><circle cx="11" cy="11" r="11" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="#7AB02C" stroke="none"
style=""></circle></svg></div><div class="_jsPlumb_endpoint
_jsPlumb_endpoint_anchor jsplumb-draggable jsplumb-droppable
_jsPlumb_endpoint_connected _jsPlumb_endpoint_full" style="position:
absolute; height: 20px; width: 20px; left: 405px; top: 118.5px;"><svg
style="position:absolute;left:0px;top:0px" width="20" height="20"
pointer-events="all" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml"><circle cx="10" cy="10" r="7" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="transparent" stroke="#7AB02C"
style="" stroke-width="3"></circle></svg></div><div
class="_jsPlumb_endpoint _jsPlumb_endpoint_anchor jsplumb-draggable
jsplumb-droppable _jsPlumb_endpoint_connected _jsPlumb_endpoint_full"
style="position: absolute; height: 20px; width: 20px; left: 452.5px; top:
166px;"><svg style="position:absolute;left:0px;top:0px" width="20"
height="20" pointer-events="all" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml"><circle cx="10" cy="10" r="7" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="transparent" stroke="#7AB02C"
style="" stroke-width="3"></circle></svg></div><div
class="_jsPlumb_endpoint _jsPlumb_endpoint_anchor jsplumb-draggable
jsplumb-droppable" style="position: absolute; height: 22px; width: 22px;
left: 451.5px; top: 70px;"><svg style="position:absolute;left:0px;top:0px"
width="22" height="22" pointer-events="all" position="absolute"
version="1.1" xmlns="http://www.w3.org/1999/xhtml"><circle cx="11" cy="11"
r="11" version="1.1" xmlns="http://www.w3.org/1999/xhtml" fill="#7AB02C"
stroke="none" style=""></circle></svg></div><div class="_jsPlumb_endpoint
_jsPlumb_endpoint_anchor jsplumb-draggable jsplumb-droppable
_jsPlumb_endpoint_connected" style="position: absolute; height: 22px;
width: 22px; left: 499px; top: 117.5px;"><svg
style="position:absolute;left:0px;top:0px" width="22" height="22"
pointer-events="all" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml"><circle cx="11" cy="11" r="11" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="#7AB02C" stroke="none"
style=""></circle></svg></div><div class="_jsPlumb_endpoint
_jsPlumb_endpoint_anchor jsplumb-draggable jsplumb-droppable
_jsPlumb_endpoint_connected _jsPlumb_endpoint_full" style="position:
absolute; height: 20px; width: 20px; left: 638px; top: 349px;"><svg
style="position:absolute;left:0px;top:0px" width="20" height="20"
pointer-events="all" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml"><circle cx="10" cy="10" r="7" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="transparent" stroke="#7AB02C"
style="" stroke-width="3"></circle></svg></div><div
class="_jsPlumb_endpoint _jsPlumb_endpoint_anchor jsplumb-draggable
jsplumb-droppable _jsPlumb_endpoint_connected _jsPlumb_endpoint_full"
style="position: absolute; height: 20px; width: 20px; left: 590.5px; top:
397px;"><svg style="position:absolute;left:0px;top:0px" width="20"
height="20" pointer-events="all" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml"><circle cx="10" cy="10" r="7" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="transparent" stroke="#7AB02C"
style="" stroke-width="3"></circle></svg></div><div
class="_jsPlumb_endpoint _jsPlumb_endpoint_anchor jsplumb-draggable
jsplumb-droppable" style="position: absolute; height: 22px; width: 22px;
left: 542px; top: 348px;"><svg style="position:absolute;left:0px;top:0px"
width="22" height="22" pointer-events="all" position="absolute"
version="1.1" xmlns="http://www.w3.org/1999/xhtml"><circle cx="11" cy="11"
r="11" version="1.1" xmlns="http://www.w3.org/1999/xhtml" fill="#7AB02C"
stroke="none" style=""></circle></svg></div><div class="_jsPlumb_endpoint
_jsPlumb_endpoint_anchor jsplumb-draggable jsplumb-droppable
_jsPlumb_endpoint_connected" style="position: absolute; height: 22px;
width: 22px; left: 589.5px; top: 300px;"><svg
style="position:absolute;left:0px;top:0px" width="22" height="22"
pointer-events="all" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml"><circle cx="11" cy="11" r="11" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="#7AB02C" stroke="none"
style=""></circle></svg></div><div class="_jsPlumb_endpoint
_jsPlumb_endpoint_anchor jsplumb-draggable jsplumb-droppable"
style="position: absolute; height: 20px; width: 20px; left: 48px; top:
429.5px;"><svg style="position:absolute;left:0px;top:0px" width="20"
height="20" pointer-events="all" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml"><circle cx="10" cy="10" r="7" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="transparent" stroke="#7AB02C"
style="" stroke-width="3"></circle></svg></div><div
class="_jsPlumb_endpoint _jsPlumb_endpoint_anchor jsplumb-draggable
jsplumb-droppable" style="position: absolute; height: 20px; width: 20px;
left: 143px; top: 429.5px;"><svg style="position:absolute;left:0px;top:0px"
width="20" height="20" pointer-events="all" position="absolute"
version="1.1" xmlns="http://www.w3.org/1999/xhtml"><circle cx="10" cy="10"
r="7" version="1.1" xmlns="http://www.w3.org/1999/xhtml" fill="transparent"
stroke="#7AB02C" style="" stroke-width="3"></circle></svg></div><div
class="_jsPlumb_endpoint _jsPlumb_endpoint_anchor jsplumb-draggable
jsplumb-droppable _jsPlumb_endpoint_connected" style="position: absolute;
height: 22px; width: 22px; left: 94.5px; top: 381px;"><svg
style="position:absolute;left:0px;top:0px" width="22" height="22"
pointer-events="all" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml"><circle cx="11" cy="11" r="11" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="#7AB02C" stroke="none"
style=""></circle></svg></div><div class="_jsPlumb_endpoint
_jsPlumb_endpoint_anchor jsplumb-draggable jsplumb-droppable
_jsPlumb_endpoint_connected" style="position: absolute; height: 22px;
width: 22px; left: 94.5px; top: 476px;"><svg
style="position:absolute;left:0px;top:0px" width="22" height="22"
pointer-events="all" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml"><circle cx="11" cy="11" r="11" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="#7AB02C" stroke="none"
style=""></circle></svg></div><svg
style="position:absolute;left:456.5px;top:176px" width="154" height="131"
pointer-events="none" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml" class="_jsPlumb_connector "><path d="M 0 8 L
0 52 M 0 50 L 0 52.5 M0 52.5 A 5 5 0 0,0 5 57.5 M 5 57.5 L 133 57.5 M133
57.5 A 5 5 0 0,1 138 62.5 M 138 60.5 L 138 67 M 138 65 L 138 125 "
transform="translate(6,0)" pointer-events="visibleStroke" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="none" stroke="white" style=""
stroke-width="8" stroke-linejoin="round"></path><path d="M 0 8 L 0 52 M 0
50 L 0 52.5 M0 52.5 A 5 5 0 0,0 5 57.5 M 5 57.5 L 133 57.5 M133 57.5 A 5 5
0 0,1 138 62.5 M 138 60.5 L 138 67 M 138 65 L 138 125 "
transform="translate(6,0)" pointer-events="visibleStroke" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="none" stroke="#61B7CF" style=""
stroke-width="4" stroke-linejoin="round"></path><path pointer-events="all"
version="1.1" xmlns="http://www.w3.org/1999/xhtml" d="M138,125 L148,105
L138,112.53999999999999 L128,105 L138,125" class="" stroke="#61B7CF"
fill="#61B7CF" transform="translate(6,0)"></path></svg><div
class="_jsPlumb_overlay aLabel" id="jsPlumb_2_34" style="position:
absolute; -webkit-transform: translate(-50%, -50%); transform:
translate(-50%, -50%); left: 462px; top: 209.170796326795px;">2-3</div><svg
style="position:absolute;left:177px;top:122.5px" width="236" height="200"
pointer-events="none" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml" class="_jsPlumb_connector "><path d="M 154 0
L 110 0 M 112 0 L -65 0 M-65 0 A 5 5 0 0,0 -70 5 M -70 5 L -70 179 M-70 179
A 5 5 0 0,0 -65 184 M -65 184 L -10 184 " transform="translate(76,6)"
pointer-events="visibleStroke" version="1.1" xmlns="
http://www.w3.org/1999/xhtml" fill="none" stroke="white" style=""
stroke-width="8" stroke-linejoin="round"></path><path d="M 154 0 L 110 0 M
112 0 L -65 0 M-65 0 A 5 5 0 0,0 -70 5 M -70 5 L -70 179 M-70 179 A 5 5 0
0,0 -65 184 M -65 184 L -10 184 " transform="translate(76,6)"
pointer-events="visibleStroke" version="1.1" xmlns="
http://www.w3.org/1999/xhtml" fill="none" stroke="#61B7CF" style=""
stroke-width="4" stroke-linejoin="round"></path><path pointer-events="all"
version="1.1" xmlns="http://www.w3.org/1999/xhtml" d="M-10,184 L-30,194
L-22.46,184 L-30,174 L-10,184" class="" stroke="#61B7CF" fill="#61B7CF"
transform="translate(76,6)"></path></svg><div class="_jsPlumb_overlay
aLabel" id="jsPlumb_2_36" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left:
361.929203673205px; top: 128px;">2-4</div><svg
style="position:absolute;left:295px;top:209px" width="130" height="113.5"
pointer-events="none" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml" class="_jsPlumb_connector"><path d="M 0 -10 L
0 -45 M0 -45 A 5 5 0 0,1 5 -50 M 5 -50 L 113 -50 M113 -50 A 5 5 0 0,1 118
-45 M 118 -45 L 118 42.5 M118 42.5 A 5 5 0 0,1 113 47.5 M 113 47.5 L 58
47.5 " transform="translate(6,56)" pointer-events="visibleStroke"
version="1.1" xmlns="http://www.w3.org/1999/xhtml" fill="none"
stroke="white" style="" stroke-width="8"
stroke-linejoin="round"></path><path d="M 0 -10 L 0 -45 M0 -45 A 5 5 0 0,1
5 -50 M 5 -50 L 113 -50 M113 -50 A 5 5 0 0,1 118 -45 M 118 -45 L 118 42.5
M118 42.5 A 5 5 0 0,1 113 47.5 M 113 47.5 L 58 47.5 "
transform="translate(6,56)" pointer-events="visibleStroke" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="none" stroke="#61B7CF" style=""
stroke-width="4" stroke-linejoin="round"></path><path pointer-events="all"
version="1.1" xmlns="http://www.w3.org/1999/xhtml" d="M58,47.5 L78,37.5
L70.46000000000001,47.5 L78,57.5 L58,47.5" class="" stroke="#61B7CF"
fill="#61B7CF" transform="translate(6,56)"></path></svg><div
class="_jsPlumb_overlay aLabel" id="jsPlumb_2_38" style="position:
absolute; -webkit-transform: translate(-50%, -50%); transform:
translate(-50%, -50%); left: 300.5px; top:
223.593805509808px;">4-4</div><svg
style="position:absolute;left:510px;top:118.5px" width="194" height="246.5"
pointer-events="none" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml" class="_jsPlumb_connector "><path d="M 148
230.5 L 183 230.5 M183 230.5 A 5 5 0 0,0 188 225.5 M 188 225.5 L 188 5 M188
5 A 5 5 0 0,0 183 0 M 185 0 L 68 0 M 70 0 L 10 0 "
transform="translate(0,10)" pointer-events="visibleStroke" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" fill="none" stroke="white" style=""
stroke-width="8" stroke-linejoin="round"></path><path d="M 148 230.5 L 183
230.5 M183 230.5 A 5 5 0 0,0 188 225.5 M 188 225.5 L 188 5 M188 5 A 5 5 0
0,0 183 0 M 185 0 L 68 0 M 70 0 L 10 0 " transform="translate(0,10)"
pointer-events="visibleStroke" version="1.1" xmlns="
http://www.w3.org/1999/xhtml" fill="none" stroke="#61B7CF" style=""
stroke-width="4" stroke-linejoin="round"></path><path pointer-events="all"
version="1.1" xmlns="http://www.w3.org/1999/xhtml" d="M10,0 L30,-10
L22.46,0 L30,10 L10,0" class="" stroke="#61B7CF" fill="#61B7CF"
transform="translate(0,10)"></path></svg><div class="_jsPlumb_overlay
aLabel" id="jsPlumb_2_40" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 697.5px;
top: 351.53318530718px;">3-2</div><svg
style="position:absolute;left:95.5px;top:316px" width="211.5" height="100"
pointer-events="none" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml" class="_jsPlumb_connector "><path d="M 195.5
10 L 195.5 45 M195.5 45 A 5 5 0 0,1 190.5 50 M 190.5 50 L 102.75 50 M102.75
50 A 5 5 0 0,1 97.75 45 M 97.75 45 L 97.75 -33 M97.75 -33 A 5 5 0 0,0 92.75
-38 M 92.75 -38 L 5 -38 M5 -38 A 5 5 0 0,0 0 -33 M 0 -33 L 0 22 "
transform="translate(9.999999999999998,44)" pointer-events="visibleStroke"
version="1.1" xmlns="http://www.w3.org/1999/xhtml" fill="none"
stroke="white" style="" stroke-width="8"
stroke-linejoin="round"></path><path d="M 195.5 10 L 195.5 45 M195.5 45 A 5
5 0 0,1 190.5 50 M 190.5 50 L 102.75 50 M102.75 50 A 5 5 0 0,1 97.75 45 M
97.75 45 L 97.75 -33 M97.75 -33 A 5 5 0 0,0 92.75 -38 M 92.75 -38 L 5 -38
M5 -38 A 5 5 0 0,0 0 -33 M 0 -33 L 0 22 "
transform="translate(9.999999999999998,44)" pointer-events="visibleStroke"
version="1.1" xmlns="http://www.w3.org/1999/xhtml" fill="none"
stroke="#61B7CF" style="" stroke-width="4"
stroke-linejoin="round"></path><path pointer-events="all" version="1.1"
xmlns="http://www.w3.org/1999/xhtml" d="M0,22
L10.000000000000002,2.0000000000000004 L7.629549558688011e-16,9.54
L-9.999999999999998,1.9999999999999993 L0,22" class="" stroke="#61B7CF"
fill="#61B7CF"
transform="translate(9.999999999999998,44)"></path></svg><div
class="_jsPlumb_overlay aLabel" id="jsPlumb_2_42" style="position:
absolute; -webkit-transform: translate(-50%, -50%); transform:
translate(-50%, -50%); left: 299.891937301077px; top:
406.889746167151px;">4-1</div><svg
style="position:absolute;left:95.5px;top:407px" width="511" height="156"
pointer-events="none" position="absolute" version="1.1" xmlns="
http://www.w3.org/1999/xhtml" class="_jsPlumb_connector "><path d="M 495 8
L 495 52 M 495 50 L 495 145 M495 145 A 5 5 0 0,1 490 150 M 490 150 L 5 150
M5 150 A 5 5 0 0,1 0 145 M 0 145 L 0 90 "
transform="translate(9.999999999999998,0)" pointer-events="visibleStroke"
version="1.1" xmlns="http://www.w3.org/1999/xhtml" fill="none"
stroke="white" style="" stroke-width="8"
stroke-linejoin="round"></path><path d="M 495 8 L 495 52 M 495 50 L 495 145
M495 145 A 5 5 0 0,1 490 150 M 490 150 L 5 150 M5 150 A 5 5 0 0,1 0 145 M 0
145 L 0 90 " transform="translate(9.999999999999998,0)"
pointer-events="visibleStroke" version="1.1" xmlns="
http://www.w3.org/1999/xhtml" fill="none" stroke="#61B7CF" style=""
stroke-width="4" stroke-linejoin="round"></path><path pointer-events="all"
version="1.1" xmlns="http://www.w3.org/1999/xhtml" d="M0,90
L10.000000000000002,110 L7.629549558688011e-16,102.46000000000001
L-9.999999999999998,110 L0,90" class="" stroke="#61B7CF" fill="#61B7CF"
transform="translate(9.999999999999998,0)"></path></svg><div
class="_jsPlumb_overlay aLabel" id="jsPlumb_2_44" style="position:
absolute; -webkit-transform: translate(-50%, -50%); transform:
translate(-50%, -50%); left: 600px; top: 481.970796326795px;">3-1</div><div
class="_jsPlumb_overlay endpointSourceLabel" id="jsPlumb_2_45"
style="position: absolute; -webkit-transform: translate(-50%, -50%);
transform: translate(-50%, -50%); left: 300.5px; top:
284.5px;">Drag</div><div class="_jsPlumb_overlay endpointSourceLabel"
id="jsPlumb_2_46" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 300.5px;
top: 379.5px;">Drag</div><div class="_jsPlumb_overlay endpointTargetLabel"
id="jsPlumb_2_47" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 252.5px;
top: 290px;">Drop</div><div class="_jsPlumb_overlay endpointTargetLabel"
id="jsPlumb_2_48" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 348.5px;
top: 290px;">Drop</div><div class="_jsPlumb_overlay endpointSourceLabel"
id="jsPlumb_2_49" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 414.5px;
top: 148px;">Drag</div><div class="_jsPlumb_overlay endpointSourceLabel"
id="jsPlumb_2_50" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 462px; top:
195.5px;">Drag</div><div class="_jsPlumb_overlay endpointTargetLabel"
id="jsPlumb_2_51" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 462px; top:
58.5px;">Drop</div><div class="_jsPlumb_overlay endpointTargetLabel"
id="jsPlumb_2_52" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 509.5px;
top: 106px;">Drop</div><div class="_jsPlumb_overlay endpointSourceLabel"
id="jsPlumb_2_53" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 647.5px;
top: 378.5px;">Drag</div><div class="_jsPlumb_overlay endpointSourceLabel"
id="jsPlumb_2_54" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 600px; top:
426.5px;">Drag</div><div class="_jsPlumb_overlay endpointTargetLabel"
id="jsPlumb_2_55" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 552.5px;
top: 336.5px;">Drop</div><div class="_jsPlumb_overlay endpointTargetLabel"
id="jsPlumb_2_56" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 600px; top:
288.5px;">Drop</div><div class="_jsPlumb_overlay endpointSourceLabel"
id="jsPlumb_2_57" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 57.5px; top:
459px;">Drag</div><div class="_jsPlumb_overlay endpointSourceLabel"
id="jsPlumb_2_58" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 152.5px;
top: 459px;">Drag</div><div class="_jsPlumb_overlay endpointTargetLabel"
id="jsPlumb_2_59" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 105px; top:
369.5px;">Drop</div><div class="_jsPlumb_overlay endpointTargetLabel"
id="jsPlumb_2_60" style="position: absolute; -webkit-transform:
translate(-50%, -50%); transform: translate(-50%, -50%); left: 105px; top:
464.5px;">Drop</div></div>

**Comment by sporritt** [comment]
there are svg elements in there.  closing this.
