### ISSUE TITLE
TargetEndpoint click : what is jsplumb behavior?

### ISSUE THREAD

**Issue by PoundrikM** [sporritt/jsPlumb#347]
Hello Simon

If user clicks on targetEndpoint , then what should be the jsPlumb behavior? Does jsPlumb think user is going to re-route the connection? If user simply clicks on targetEndpoint and does not re-route the connection (by drag & drop feature), so connector should get removed? if yes then how we can stop this? any jsPlumb API for this?.

kindly help.

Regards,
Milind

**Comment by sporritt** [comment]
there is no default behaviour for endpoint click.

would it be possible for you to raise questions like this in the google group? i prefer to keep github just for issues or enhancement requests. thanks.

**Comment by PoundrikM** [comment]
Thanks Simon.

Could you please suggest my next step?

Regards,
Milind

**Comment by PoundrikM** [comment]
Simon -  I have posted it on google group now. Please suggest my next step?
