### ISSUE TITLE
dropOptions drop or onDrop which is correct? Documentation issue - Minor

### ISSUE THREAD

**Issue by dlinx** [sporritt/jsPlumb#348]
Error in documentation
In the document there are two example, in which drop event handler is used, here are

var endpointOptions = { 
  isSource:true, 
  isTarget:true,
  endpoint: [ "Dot", { radius:30 } ],
  style:{fillStyle:'blue'},
  connector : "Straight",
  connectorStyle: { lineWidth:20, strokeStyle:'blue' },
  scope:"blueline",
  dropOptions:{ 
    drop:function(e, ui) { 
      alert('drop!'); 
    } 
  }  
}; 

and 

var endpointOptions = { 
isSource:true, 
isTarget:true,
endpoint: [ "Dot", {radius:30} ],
style:{ fillStyle:'blue' },
maxConnections:-1,
connector : "Straight",
connectorStyle: { lineWidth:20, strokeStyle:'blue' },
scope:"blueline",
dropOptions:{ 
  onDrop:function(e, ui) { 
      alert('drop!'); 
    } 
  }  
}; 

so Which is event handler? drop or onDrop??

**Comment by sporritt** [comment]
there is of course a fairly easy way you could have found out the answer to this question....

**Comment by sporritt** [comment]
anyway...fixed in 1.7.5 dev

![image](https://cloud.githubusercontent.com/assets/262720/6889199/35d3be7a-d6dd-11e4-9103-81d313125172.png)


![image](https://cloud.githubusercontent.com/assets/262720/6889201/3f862570-d6dd-11e4-8549-2b487708d47b.png)
