### ISSUE TITLE
Position of nested draggables calculated incorrectly

### ISSUE THREAD

**Issue by DawnPaladin** [sporritt/jsPlumb#352]
jsPlumb/Katavorio seems to have no trouble nesting one draggable inside another draggable. However, if you add jsPlumb endpoints to either element, any further dragging will cause the positions of the endpoints and/or the elements to be calculated incorrectly. [See this JSFiddle.](http://jsfiddle.net/jharris/znjnw9d2/)

**Comment by sporritt** [comment]
the container endpoints are in fact irrelevant, you can drag the container before adding child endpoints and you get this:

![image](https://cloud.githubusercontent.com/assets/262720/7110262/ca48900c-e1f1-11e4-8224-be59401fd8e5.png)

**Comment by DawnPaladin** [comment]
It looks to me like adding endpoints to either the container or the cell causes issues. Here are the test results I'm seeing:

1. Load page, drag each container. Everything functions normally.
2. Click "Add container endpoints". Dragging the container now works normally, but when you drag the cell it's offset from the mouse cursor.
3. Click "Add cell endpoints". The container still drags normally. When you drag the cell, its handles follow the cursor, but the cell is offset. Releasing the cursor snaps the handles to the cell's (incorrect) location.
4. Reload the page to reset the test. Drag the container a bit, then click "Add cell endpoints". Now dragging the container will cause the cell endpoints to move further than they should (as shown in your screenshot). Dragging the cell causes them to return to their correct position.
5. Click "Add container endpoints". Now dragging the container will cause both sets of endpoints to wander as they did in step 4.

Are you seeing the same behavior? (I'm using Chrome on Windows.)

**Comment by sporritt** [comment]
yes i do see all of those things. i hadn't seen point 5; i quite like it, it feels like some kind of first person 3d experience.

**Comment by DawnPaladin** [comment]
Yeah, it's fun. :-) I'm hoping you'll be able to fix it, though--it's blocking my project from moving forward.

**Comment by sporritt** [comment]
I see. If you find that the pace at which I am able to address this - due to such things as paying my rent, say - I would encourage you to not forget that you have access to the source and a debugger.

**Comment by DawnPaladin** [comment]
I was just hoping to get this marked as either "bug" or "wontfix". Or if this isn't a high priority, that's fine--just let me know, so I can make other arrangements.

**Comment by sporritt** [comment]
Its something I'd _like_ to get into 1.7.6 but at this point its un CV Lear if I will have the time. Sorry I can't be any more specific.

**Comment by DawnPaladin** [comment]
That helps, thank you!

**Comment by sporritt** [comment]
@DawnPaladin quick update on this - wont make it into 1.7.6. needs more thought (from me, not you!)

**Comment by sauerman** [comment]
Is this forgotten?

**Comment by sporritt** [comment]
no, not forgotten. not scheduled right now, but not forgotten.

**Comment by sauerman** [comment]
k. my workaround is something like this:
```javascript
      jsPlumb.draggable(el, {
        drag (event) {
          // THIS FIXES A BUG IN JS-PLUMB ->
          // https://github.com/sporritt/jsPlumb/issues/352
          el.style.left = (event.pos[0] - parent.position.x) + 'px';
          el.style.top = (event.pos[1] - parent.position.y) + 'px';
        },
      });
```
parent beeing the outer-draggable.
Its not great and somethimes you get tiny glitches.

**Comment by sporritt** [comment]
@DawnPaladin it's been a while since you raised this, i know, but chances are a fix will make it into 2.1.0, which will be out in the next couple of weeks or so.

**Comment by DawnPaladin** [comment]
Excellent! Thank you for working on this. Looking forward to the new version. :smile:

**Comment by sporritt** [comment]
it's been quite some time, but 2.1.0 has (will have - releasing in the next week) support for groups. there are a bunch of more recent issues covering various aspects of it.  closing this one out.
