### ISSUE TITLE
HTML <select> multiple disabled in Chrome when draggable

### ISSUE THREAD

**Issue by Timathom** [sporritt/jsPlumb#353]
With vanilla jsPlumb in the latest version of Chrome (41), HTML select multiple is disabled when the parent element is draggable. This does not happen in Firefox (or in Chrome with the jQuery flavor of jsPlumb). See http://jsfiddle.net/fwdo0jfb/1/.

**Comment by sporritt** [comment]
this would be an issue for [Katavorio](https://github.com/jsplumb/katavorio), the drag library embedded in vanilla jsplumb.

**Comment by sporritt** [comment]
corresponding Katavorio issue :  https://github.com/jsplumb/katavorio/issues/16

**Comment by sporritt** [comment]
fixed in 1.7.6 dev.
