### ISSUE TITLE
Endpoint hoverPaintStyle outlineWidth doesn't work

### ISSUE THREAD

**Issue by jezaman** [sporritt/jsPlumb#354]
Hi,

hoverPaintStyle: {outlineWidth: 2}
seems to have no effect. However, if i put 
hoverPaintStyle: {fillStyle: "red"} 
at the same place in my code, I do notice the endpoint turn red upon hover. 
Could it be that the outlineWidth parameter somehow doesn't work for endpoint hover styles? 
I got it working for the connector, though.

**Comment by sporritt** [comment]
that's right, outlineWidth doesnt work for endpoints.

**Comment by jezaman** [comment]
Thanks for your fast answer!
Is that a bug? or ?
Your API mentions: outlineWidth - width of the outline for an Endpoint or Connector. An integer.
Wasn't sure if the parameter name might have changed recently and the API not updated or so.

**Comment by sporritt** [comment]
hmm..actually i was pretty sure it wasnt supported in endpoints, so perhaps the API doc is at fault. i will take a look at this tomorrow...

**Comment by sporritt** [comment]
...so outlineWidth is supported, sort of.  Take a look at this demo:

http://jsplumb.org/demo/flowchart/dom.html

The small endpoints are achieved via this code:

```
// the definition of source endpoints (the small green ones)
        sourceEndpoint = {
            endpoint: "Dot",
            paintStyle: {
                strokeStyle: "#7AB02C",
                fillStyle: "transparent",
                radius: 7,
                lineWidth: 3
            },
```

ie. without `outlineWidth` or `outlineColor`.  But if you were to supply both of those, then the endpoint SVG renderer would just do this with them:

```
if (s.outlineColor) {
  s.strokeWidth = s.outlineWidth;
  s.strokeStyle = _ju.convertStyle(s.outlineColor, true);
}
```

**Comment by sporritt** [comment]
(i know that's not a `hoverPaintStyle` example but the code used is identical when hovering).

I can get this:

![image](https://cloud.githubusercontent.com/assets/262720/7104155/ed4f8052-e10f-11e4-81f0-ea670071cdf4.png)

by switching the `hoverPaintStyle` directive to:

```
//hoverPaintStyle: endpointHoverStyle,
            hoverPaintStyle: {
                strokeStyle: "red",
                fillStyle: "transparent",
                radius: 7,
                lineWidth: 4
            },
```
