### ISSUE TITLE
Connector deletion on single click on TargetEndPoint using dom.jsPlumb-1.6.2.js version.

### ISSUE THREAD

**Issue by PoundrikM** [sporritt/jsPlumb#356]
Hi Simon
I am facing issue of connector deletion when user single/double click on target endpoint. I am using dom.jsPlumb-1.6.2.js version of jsPlumb:

Here is the sample code:
function onLoadDesignMode()
{
jsPlumb.bind('ready', function () {
jsPlumb.Defaults.Container = $("#Page");  
	var sourceColor = "#ff1111";
	var targetColor = "#8F00FF";
	var source1 = { anchor: "RightMiddle",endpoint: ["Dot", { radius: 5}],paintStyle: { fillStyle: sourceColor },isSource:true,scope: "green dot",  connectorStyle: { strokeStyle: sourceColor, lineWidth: 2 }, maxConnections: -1, connector: "Flowchart"};
	var target1 = { anchor: "LeftMiddle",endpoint: ["Dot", { radius: 5}],paintStyle: { fillStyle: targetColor },isTarget:true,scope: "green dot",  connectorStyle: { strokeStyle: sourceColor, lineWidth: 2 }, maxConnections: -1, connector: "Flowchart"};
};
jsPlumb.addEndpoint(id1, {connectionsDetachable:true},source1);
jsPlumb.addEndpoint(id2, {connectionsDetachable:true},target1);
}); 
}
Could you please let me know how to stop deletion of connector.

Note: This issue is not reproducible when i am using jsPlumb1.7.5 version but I can not use this version as my whole development has been done using dom.jsPlumb-1.6.2.js. so it will be very risky at changing it last moment.

Is there any difference both the version of jsPlumb with respect to handling connector deletion?

Kindly help.

**Comment by sporritt** [comment]
the changelog is here

http://jsplumb.org/doc/changelog.html

I dont have the time to support any version of jsPlumb other than the current one.

please try to use this issue tracker as an issue tracker and not as a place to have discussions. there is a google group for discussions:

https://groups.google.com/forum/?fromgroups#!forum/jsplumb
