### ISSUE TITLE
Detaching a connection causes weird endpoint behaviour

### ISSUE THREAD

**Issue by aravindakrishna** [sporritt/jsPlumb#357]
I am detaching a connection on listening for the "connection" event using this:
jsPlumb.detach(info.connection)
However, this causes the endpoint DOM element to be deleted (using console on chrome I was no longer able to access the endpoint using its id) and detached from the parent div element to which the endpoint is attached. The latter causes the endpoint to be in a static position even when the parent div is dragged around.
Also, I cannot make any more connections using that endpoint(obviously). 
P.S. The problem is only with the sourceEndpoint and not with the targetEndpoint to which the connection is made. And I am doing all these only on connections made with mouse.
Details:
Using jsplumb v1.7.5 min js

**Comment by sporritt** [comment]
can you please supply a jsfiddle demonstrating the issue.

**Comment by aravindakrishna** [comment]
i got around the problem by using beforeDrop listener, and sorry I can't create a jsFiddle. 
After reporting this issue, I also saw others had raised the same issue before so I guess you could use those for reference.

**Comment by sporritt** [comment]
do you have any specific issue numbers in which this is discussed?

**Comment by aravindakrishna** [comment]
I think I saw the same in the google groups. I found this:
https://groups.google.com/forum/?fromgroups#!searchin/jsplumb/endpoint$20detach/jsplumb/F3MZcNwhqio/xHww-0JVkO8J
