### ISSUE TITLE
Dragable property

### ISSUE THREAD

**Issue by xxlali** [sporritt/jsPlumb#358]
I am trying to integrate jsPlump to Angular Gantt for task dependency. I have added endpoints and connections between endpoints. But when I move a task endpoints and connections do not move. I have tried to use instance.draggable function, but this time end points move separetly from tasks. What can I do to implement this property succesfully.

**Comment by sporritt** [comment]
Please do nor use this issue tracker as a discussion group. There is a Google group for questions like this. 

When/if you do post, it is usually a good idea to supply a jsfiddle showing what you currently have working and what your specific problem is.
