### ISSUE TITLE
jsPlumb in bootstrap tab

### ISSUE THREAD

**Issue by absentdream** [sporritt/jsPlumb#359]
hi i have an issue with jsPlumb in a bootstrap tab. when i switch to the relevant tab (one containing the jsPlumb) any new connectors draw appear at the top left of the container.. unless i move the nodes first then the new connectors are drawn from the top left of the node. 

at present the only way i can get it to put them in the right place is switch to tab, move all nodes and issue a repaintEverything then every thing works fine.. so i presume its an issue with the jsPlumb being fired up with the container on a non active tab, and thus cannot calculate node positions, and size...

is the way to force it to re-fire and thus get correct node sizes and positions...

many thanks

**Comment by sporritt** [comment]
that's right. if the nodes are not visible jsPlumb cant figure out where to paint anything. you have to issue a repaint command when your nodes are visible and have been placed.

**Comment by absentdream** [comment]
Thats what i thought.. but i have to move the nodes and then issue a repaint or it will only draw new connectors in top left of container...dose repaintEverything requery nodes x,y, width and height ?

**Comment by sporritt** [comment]
Yes. Your nodes need to be positioned before you repaint.

**Comment by alanhg** [comment]
![image](https://user-images.githubusercontent.com/9245110/34200470-2aa1afa4-e5ac-11e7-9535-c8615f2471f8.png)
anchor position is wrong, How to solve it?

![image](https://user-images.githubusercontent.com/9245110/34200525-5f565b5a-e5ac-11e7-8c27-507dffa3bc67.png)

I use jsplumb in bootstrap.
