### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by PhiLhoSoft** [sporritt/jsPlumb#360]
I am reading the documentation at http://jsplumb.org/doc/home.html

First remark: these pages have no title tag set, it looks ugly in the tabs of the browsers. I suggest to generate this tag.

Second remark: I found a dead link, to http://jsplumb.org/doc/styling-via-css
The link is given in the Z-index Considerations section.

Lastly, I stumbled upon https://jsplumbtoolkit.com/doc/ which doesn't has the issue, the https://jsplumbtoolkit.com/doc/styling-via-css page is visible.
It is a bit confusing. The GitHub blurb at the top of https://github.com/sporritt/jsPlumb points to the toolkit site, making it somehow official, while the first link in the readme ("_please do take the time to read the documentation_") points to the org site...

**Comment by sporritt** [comment]
they are the same site. the html suffix thing is an apache configuration issue.

**Comment by sporritt** [comment]
i'm going to close this out as there's a new site going up shortly which does not have these issues. and the org site will be gone.
