### ISSUE TITLE
unbinding events

### ISSUE THREAD

**Issue by michalvvv** [sporritt/jsPlumb#369]
Recently [not last time!] I am using your library. There is one thing that causes problems for me - binding and unbinding events for connections.
I am creating my own, additional 'mouseover' events which I once bind and later unbind, but connection's unbinding takes only one argument - event name. So when I want to unbind my own handler for `mouseover`, it unbinds also built-in bindings for hovering connections. It would be nice if you added unbinding for specific handlers, like in jQuery.

**Comment by sporritt** [comment]
when you say, "last time i am using your library", do you mean you're not going to use it anymore?

**Comment by michalvvv** [comment]
No, no! I wrongly translated it from my language. I meaned "recently"...

**Comment by sporritt** [comment]
ah! i thought it might be that. ha ha.  ok.

yes i looked in the code.  it should do what you're suggesting i think.

**Comment by sporritt** [comment]
i've put this into the 1.7.6 dev branch.  apidocs look like this:

```
/**
   * Clears either all listeners, or listeners for some specific event, or just some listener. You can call this method
   * with zero, one or two arguments: with zero arguments, all listeners are cleared. With one argument that is a string, all listeners for
   * the specified event type are cleared. With one argument that is a function, it is removed from the appropriate event list.
   * With two arguments, the first is an event type, and the second is a function to be unbound. In fact this is perhaps unnecessary
   * given that you can unbind a function just by passing it.
   * @method unbind
   * @param {String|Function} [eventOrListener] If a string, constrains the clear to just listeners for the event identified by the string. If a Function, unbinds this function wherever it may have been bound.
   * @param {Function} [listener] If provided, removes just this listener for the given event.
   */
```
