### ISSUE TITLE
No scrolling possible 

### ISSUE THREAD

**Issue by julius90** [sporritt/jsPlumb#370]
First of all thank you for jsPlumb, really great work. It fits nearly perfect for my application.
Unfortunately my div container (#stm) doesn't scroll if I reach the borders at the right and bottom with my draggable elements (.element). I tried many different thinks to figure it out why it doesn't work but could not find a solution.
Hopefully you can help me.
Here is my structure:
```
HTML:
<div class=body>
	<div> class="menu">...</div>
	<div> class="main">
		<div> class="page-header">...</div>
		<div> id="container" class="content">
			<div> id="navbar">...</div>
			<div> id="stm" class="content">
				<div id="state0" class="element">...</div>
			</div>
		</div>
	</div>
	<div> class="properties">...</div>
</div>
```
```
CSS:
.body {
	position: absolute;
	display: flex;
	right: 0;
	left: 0;
}
.main {
	flex: 1;
	display: flex;
	flex-direction: column;
}
.page-header {
	height: 30px;
}
.content {
	flex: 1;
	display: flex;
	overflow: auto;
}
#stm {
	position: relative;
	overflow: auto;
}
.element {
	position: absolute;
	z-index: 4:
}
```

**Comment by sporritt** [comment]
i think actually this is a limitation of [Katavorio](https://github.com/jsplumb/katavorio), the dragging library used by vanilla jsPlumb. It is planned as an enhancement but the work has not yet been scheduled.

in the meantime you could possibly try using the jQuery flavour of jsPlumb, with jQuery UI. Normally I don't recommend that, but in this case it might get you what you want.

**Comment by julius90** [comment]
Thank you for answering me. I actually use jQuery instead of vanilla.
Now I have found a way to solve it a bit, but not like in your examples.

**Comment by LeCoupa** [comment]
@julius90 how did you do it if it is not too late?
