### ISSUE TITLE
Bug: endpoint locations incorrect when using margins

### ISSUE THREAD

**Issue by tmmls** [sporritt/jsPlumb#374]
Hi,

I've encountered this bug:

When dragging a draggable element (made draggable using jsPlumb),and the element contains a css based margin, the endploints on the element are displayed in the wrong position. 

When the element is released, the position is still wrong. Repainting all elements after the release will fix this issue, but not always.

**Comment by sporritt** [comment]
This is a known issue. If you've made something draggable then it will be positioned absolute, and so having a margin on the element doesn't make a lot of sense.

**Comment by a-pavlov-parc** [comment]
@sporritt I have the same issue. If I have a margin-left of some element which parent of container element it doesn't calculate correct location of endpoints. Edpoints moved appropriate right

And if I have some paddings or some element with margin top or bottom above the container the first it paint correct, but after dropping some element it's beginning to be worse. Like this
http://take.ms/dGTkF

Could it be fixed?
Thanks

**Comment by sporritt** [comment]
I don't think it's a bug. There is no point in putting margins on elements that are positioned absolute, except, perhaps, in a few fairly specific use cases. But certainly not for absolute positioned elements that you're going to be dragging.
