### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by afferently** [sporritt/jsPlumb#375]
I can't seem to get grid working with vanilla jsPlumb by supplying grid to draggable.

Do I need to load Katavorio and well as jsPlumb?

I might be wrong though it appears that it's not working on your vanilla flow chart demo either.

Strangely, grid works as expected when I use Katavorio though there doesn't appear to be a snapToGrid() function as documented.

**Comment by sporritt** [comment]
Katavorio is bundled into vanilla jsPlumb.

on the flowchart demo the snap to grid is working (at least for me, on a mac, on chrome/ff/safari):

http://jsplumb.org/demo/flowchart/dom.html

but it is admittedly quite subtle.

This is the snapToGrid function on Katavorio:

![image](https://cloud.githubusercontent.com/assets/262720/7725332/fce1ef3c-ff3c-11e4-984a-8580bc458a26.png)

or do you mean that method is not available on jsPlumb?

**Comment by afferently** [comment]
Ahh yes, I noticed using grid in jsPlumb it snaps to a grid if you drag near it though you can still actually place an element anywhere.

In Katavorio the grid function limits the movement precisely to the grid which is what I'm after.

Is this possible in jsPlumb?

**Comment by sporritt** [comment]
I guess you're using Katavorio 0.5 if you got it from Github. Later versions of Katavorio (why are they not merged to master?  good question) introduced the snap behaviour you're talking about, and jsPlumb currently has Katavorio 0.6.

There is now the concept of a `snapThreshold`, whose default value is 5 pixels. Setting that to 0 should get snap back to how you want it.

**Comment by sporritt** [comment]
(and you can pass that in through jsPlumb, yes)

**Comment by afferently** [comment]
Ahh ok, how do I set the snapThreshold?

**Comment by afferently** [comment]
Actually it appears that 0 does nothing, if i set it to =>35 then it snaps as expected!

What are the units for threshold?

**Comment by sporritt** [comment]
Ah..ok. great!

**Comment by miloszw** [comment]
Somewhat related; how can I access Katavorio through jsPlumb to call its grid-related methods? Also, how do I set the `snapThreshold` property exactly?

**Comment by sporritt** [comment]
`snapThreshold` can be set in the params to the `draggable` call.

The API doesn't expose the underlying Katavorio instance at the moment. Is there a specific reason you need it to, or were you just asking with respect to the question about snapThreshold?
