### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by PhiLhoSoft** [sporritt/jsPlumb#379]
http://www.jsplumb.org/apidocs/classes/jsPlumbInstance.html#method_connect
>  [type] String optional
> Optional type for the Connection.

Looks like it is not named `type`, but `connector` (according to the source code).
And http://www.jsplumb.org/doc/connect-examples.html shows more parameters...
The API reference should be more exhaustive or should link to these doc pages explicitly.

**Comment by sporritt** [comment]
`type` is a valid parameter for the `connect` call.

**Comment by PhiLhoSoft** [comment]
OK, then my criticism is about the terseness of the description: what is a "type for the Connection"? What are the valid values? The http://www.jsplumb.org/apidocs/classes/Connection.html reference also talks about types without indicating what they are. Apparently, we can have several types for a connector... I see a sentence "See the jsPlumb documentation for a full discussion of types." which is seen in other places of the reference. That's nice, but a link would be more useful. :smile: I hope it will be easier to do once you stabilized the site update.

And I think the `connector` parameter should be in the reference of `connect()` as it is an important parameter (it was the one I was looking for, wanting a straight one, instead of the default Bézier one).

NB: I try to do positive feedback to the documentation, which is good and relatively comprehensive, hoping to help you to improve it, from the point of view of a beginner... :wink: 

OK, I found an explanation about types in the http://www.jsplumb.org/doc/types.html page. A useful feature, indeed.
Another confusing point is in http://www.jsplumb.org/doc/connectors.html which tells: "_for each Connector type_" where "type" refers here to "connector" (if I understood correctly...). Side note for this page: the "basic-concepts#definitions" part looks like some markup left uninterpreted.

HTH.

**Comment by sporritt** [comment]
yes keeping docs up to date and useful is one of the more difficult - or perhaps just time-consuming - aspects of running a project like this. in my ideal world the API docs and the other docs would merge into one, somehow.  Probably an extension to the yuidoc stuff would be good. i'm about to do a new release so i'll consider your suggestions as i go through the docs.
