### ISSUE TITLE
1.7.5 - instance.detach(connection) will detach source endpoint as well

### ISSUE THREAD

**Issue by johnsonlin** [sporritt/jsPlumb#381]
I binded `connection` event with a detach method.
But when I detach the connection, it will also detach the source endpoint.
After that, the detached the source endpoint won't move or do anything.
Here's a quick demo
http://plnkr.co/edit/qtoNe8Jg3fDjf5couMpk?p=preview

the reason I bind `connection` event is because I need to make a API call after connecting 2 elements. if I get an error, i need to detach the connection.
Since `beforeDrop` doesn't support promise, I had no choice but to check after the connection is established.

Could you please look into this?

**Comment by johnsonlin** [comment]
@sporritt 
Any suggestions on how I achieve this?

**Comment by sporritt** [comment]
i just took a look at this. can you make the demo any more simple? this is what it looks like to me

![image](https://cloud.githubusercontent.com/assets/262720/7905629/e62b5884-085e-11e5-857f-7d39e4bbef12.png)

**Comment by johnsonlin** [comment]
@sporritt 
Really sorry that my demo.css was linked to my local env.
Could you please have a look now?
I have also simplified the demo so it has only 2 blocks

**Comment by sporritt** [comment]
this looks like a bug, although not one that you couldn't workaround. you could return false in your beforeDrop and then make the connection manually yourself (via `connect`) after your server hits you back.

**Comment by sporritt** [comment]
(and thanks for making that a little tidier!)

**Comment by johnsonlin** [comment]
Thanks for the tip Simon.
But is this going to be fixed in the future?
And would you consider using promise for `beforeDrop` and `beforeDetach` events?

**Comment by sporritt** [comment]
i will take a look at the bug and see if i can fix it for 1.7.6; i dont know yet how much work it will be.

as for a promise for these events, "possibly" is about the best i can do.  it might be quite invasive on the code; it might be easier to just introduce some new concept. i will need to take a look. conceptually i like the idea of it though.

**Comment by johnsonlin** [comment]
Thanks Simon : )
Can't wait to see your new release!

**Comment by sporritt** [comment]
@johnsonlin i think i have fixed this now in the 1.7.8 dev branch

**Comment by Emiya0306** [comment]
@sporritt  Hey, is it support asynchronous beforeDrop Function for now?
