### ISSUE TITLE
Connections move or brake on resize

### ISSUE THREAD

**Issue by rankill** [sporritt/jsPlumb#382]
Hi guys. I really liked your plugin it's awesome. But I couldn't implemented because I found a flaw.  =( 
When I do a connection and I change the size of the screen The lines or connections don't follow sooooo mmmmmm could you give a hint how I can help, or should I wait.¿? 

Thanks a lot. 

Sincerely
Luis. 

![sample](https://cloud.githubusercontent.com/assets/6987914/7863033/866ac610-051f-11e5-8716-0c36ce11a16a.png)

**Comment by sporritt** [comment]
without any code to look at i don't know what exactly is happening here. certainly when you resize that demo on the jsPlumb site you do not see this problem.

you might want to look at the `repaintEverything` function

http://jsplumb.org/apidocs/classes/jsPlumbInstance.html#method_repaintEverything

**Comment by michaelmior** [comment]
I ran into the same issue and `repaintEverything` doesn't solve anything for me. I know it's hard without seeing code, but any ideas what might be going on?

**Comment by sporritt** [comment]
it might be something about margins. i closed the issue because two weeks had elapsed with no feedback and i like to keep the issue list clean. if you can reproduce the problem in a jsfiddle or similar it would be helpful.

**Comment by michaelmior** [comment]
Yup, that's usually my first step. if I get a chance to boil it down, I'll post here.

**Comment by besingamkb** [comment]
@sporritt can you update the method_repaintEverything link? it is not found

**Comment by sporritt** [comment]
https://jsplumbtoolkit.com/community/apidocs/classes/jsPlumbInstance.html#method_repaintEverything

but it's just `jsPlumb.repaintEverything()`
