### ISSUE TITLE
jsPlumb.setDraggable fails for an array of elements

### ISSUE THREAD

**Issue by miloszw** [sporritt/jsPlumb#383]
`setDraggable` seems only to apply to the first element when passed in as an array. See [fiddle](http://jsfiddle.net/5jo4wb2u/).

**Comment by sporritt** [comment]
Targeting 1.7.6

**Comment by sporritt** [comment]
update on this: it's actually not when the argument is an array; the problem here is that the result of `getElementsByClassName` is an `HTMLCollection`, which jsPlumb does not recognise as being list-like.

**Comment by sporritt** [comment]
fixed in 1.7.6 dev
