### ISSUE TITLE
jsPlumbInstance.draggable('ObjId',{ containment:"dragDrop"}) don't calc offsets

### ISSUE THREAD

**Issue by paulsen-it** [sporritt/jsPlumb#385]
Hello Together,
I found a problem with jsPlumbInstance.draggable('ObjId',{ containment:"dragDrop"}). This don't calculate the offset. If the Div "dragDrop" have margin, float or something else.
Here a Live-Demo:
http://jsfiddle.net/cmuzp89u/
Here you see, that it work, the windowX Elements stops, but not in the blue Box. The stop box is displaced.
Best wishes
Björn

**Comment by sporritt** [comment]
that's right, margins are not included in the calculations.  if you're making something draggable you're positioning it absolute and it doesnt make sense for it to have a margin. No change will be made to this behaviour.

**Comment by paulsen-it** [comment]
And what is with float? Look at the link above. So it is not correct and no margin is set. margin was a example, yes you're right. I don't deliberate.
Look at your demo pages, all objects you can put outside, but than the Objects are lost. You can not Drag them back, if they are one time going outside. So the option "containment" is important, but don't work correctly. Or do I something wrong at the example above?

**Comment by paulsen-it** [comment]
Here is the Solution:
File lib/katavorio-0.6.js
Line 230:
this.constrain = typeof this.params.constrain === "function" ? this.params.constrain  : (this.params.constrain || this.params.containment) ? function(pos) {
            var containmentObj = document.getElementById(this.params.containment); // New
            var offsetX = containmentObj.offsetLeft;  // New
            var offsetY = containmentObj.offsetTop;  // New
            /* This ist wrong:
            return [
                Math.max(0, Math.min(constrainRect.w - this.size[0], pos[0])),
                Math.max(0, Math.min(constrainRect.h - this.size[1], pos[1]))
            ];*/
            return [  // This is right
                Math.max(offsetX, Math.min(constrainRect.w - this.size[0]+offsetX, pos[0])),
                Math.max(offsetY, Math.min(constrainRect.h - this.size[1]+offsetY, pos[1]))
            ];
        } : function(pos) { return pos; };

**Comment by sporritt** [comment]
Oh i see, right....the container.  The lesson here is to never look at issue reports first thing in the morning. Thanks for the fix. I will move this over to katavorio and apply it.

**Comment by sporritt** [comment]
Here's the Katavorio issue

https://github.com/jsplumb/katavorio/issues/20

targeting 0.7 katavorio and jsPlumb 1.7.6

**Comment by paulsen-it** [comment]
I changed the calculation again. Perhaps it solve also your Problem?

this.constrain = typeof this.params.constrain === "function" ? this.params.constrain  : (this.params.constrain || this.params.containment) ? function(pos) {
            var containmentObj = document.getElementById(this.params.containment);
            for (var lx=0, ly=0; containmentObj != null; lx += containmentObj.offsetLeft, ly += containmentObj.offsetTop, containmentObj = containmentObj.offsetParent);
            var offsetX = lx;
            var offsetY = ly;
            /*var offsetX = containmentObj.offsetLeft;
            var offsetY = containmentObj.offsetTop;*/
            // BP 2015-06-09 13:41: 
            /*return [
                Math.max(0, Math.min(constrainRect.w - this.size[0], pos[0])),
                Math.max(0, Math.min(constrainRect.h - this.size[1], pos[1]))
            ];*/
            return [
                Math.max(offsetX, Math.min(constrainRect.w - this.size[0]+offsetX, pos[0])),
                Math.max(offsetY, Math.min(constrainRect.h - this.size[1]+offsetY, pos[1]))
            ];
        } : function(pos) { return pos; };

**Comment by sporritt** [comment]
Hello

thanks for the update.

i just took a closer look at your original fiddle and noticed that the styles for the `demo` div had invalid CSS:

![image](https://cloud.githubusercontent.com/assets/262720/8775379/efacf12c-2f2a-11e5-8b66-266484a009d6.png)

it says `relative` without `position:`.  If I put `position:relative` in I see the containment working:

![image](https://cloud.githubusercontent.com/assets/262720/8775388/14eb0ed8-2f2b-11e5-8a8c-86d39a8f5131.png)

**Comment by paulsen-it** [comment]
oh, yes this is the Bug, without "position:relative", and without "relative". I delete not all. Sorry. But with my last code changes this should work.

**Comment by sporritt** [comment]
tracking in Katavorio.
