### ISSUE TITLE
Error: "Object doesn't support this action"

### ISSUE THREAD

**Issue by jwerre** [sporritt/jsPlumb#388]
I'm getting this error in IE9: `Object doesn't support this action`

at line number 11177:

	if (document.createStyleSheet && document.namespaces) {			
		
		var ruleClasses = [
				".jsplumb_vml", "jsplumb\\:textbox", "jsplumb\\:oval", "jsplumb\\:rect", 
				"jsplumb\\:stroke", "jsplumb\\:shape", "jsplumb\\:group"
			],
			rule = "behavior:url(#default#VML);position:absolute;";

		jsPlumbStylesheet = document.createStyleSheet();

		for (var i = 0; i < ruleClasses.length; i++)
			jsPlumbStylesheet.addRule(ruleClasses[i], rule);

		// in this page it is also mentioned that IE requires the extra arg to the namespace
		// http://www.louisremi.com/2009/03/30/changes-in-vml-for-ie8-or-what-feature-can-the-ie-dev-team-break-for-you-today/
		// but someone commented saying they didn't need it, and it seems jsPlumb doesnt need it either.
		// var iev = document.documentMode;
		//if (!iev || iev < 8)
			document.namespaces.add("jsplumb", "urn:schemas-microsoft-com:vml");
		//else
		//	document.namespaces.add("jsplumb", "urn:schemas-microsoft-com:vml", "#default#VML");
	}

I should mention that I'm using require.js to import jsplum as a module.

**Comment by sporritt** [comment]
I'd need a jsfiddle or something to help you with this one. jsPlumb works in IE9 so presumably the issue here is something to do with the inclusion of require js.

**Comment by sporritt** [comment]
@jwerre any update on this?
