### ISSUE TITLE
Increase drop zone of endpoint 

### ISSUE THREAD

**Issue by Jiiieeef** [sporritt/jsPlumb#389]
Hello, 
I would like to know if it's possible to increase the zone where  we drop the endpoint to attach it to another endpoint. See the image: 
![example](https://cloud.githubusercontent.com/assets/6318981/8188441/593408d2-1456-11e5-9d8e-79befb01692e.png)

Thanks.

**Comment by sporritt** [comment]
answered in the groups.

You could make the endpoint larger, but I suspect you mean with something transparent.

Or you could add a large transparent border to the endpoint via setting the `cssClass` on the endpoint.
