### ISSUE TITLE
Bug with Anchors and Scroll Offset

### ISSUE THREAD

**Issue by stats** [sporritt/jsPlumb#390]
Windows 7 with Google Chrome Version 43.0.2357.124 m

https://gist.github.com/stats/93a38bc6fb6462a908aa
(tried creating a fiddle for this, but reproducing this bug when frames are being used is tough)

1. Scroll down so that you can see the div and the anchor. It is important that you scroll. 
2. Reload the page (it will auto scroll to place the div in your viewport)

**Expected:** The anchor **a1** should be positioned at the BottomMiddle of the **window1** div

**Results:** You will see the anchor **a1** offset up the page in inverse proportion to the distance you scrolled down.

**Comment by stats** [comment]
I have updated the gist to contain two divs and two anchors. Another most likely related issue can be reproduced by.

1. Scroll down so that you can see both divs.
2. Attempt to move an anchor.

**Expected:** The anchor will be positioned at the mouse cursor.

**Result:** The anchor is offset up the page in inverse proportion to the distance you scrolled down from the mouse.

**Comment by sporritt** [comment]
would you mind trying this with the latest 1.7.6 dev version?  i suspect this is a repeat of an issue that several people have filed against 1.7.5.

**Comment by stats** [comment]
Yes, this is resolved in 1.7.6

Sorry for creating a duplicate issue.

**Comment by sporritt** [comment]
no problem, thanks for following up.

**Comment by hopewise** [comment]
1.7.6 saved my hard working, thanks :+1:
