### ISSUE TITLE
Overlapping of connection

### ISSUE THREAD

**Issue by pkshah1987** [sporritt/jsPlumb#391]
Hi,

I have modified jsPlumb flowchart code to dynamically generate connection and anchors at predefined position. I have issue when the connection is made there is overlapping between 2 connections.

Is there a way to prevent overlapping and dynamically change connection path to avoid overlapping?

Attached the image with overlapping issue.
![overlappingconnection](https://cloud.githubusercontent.com/assets/12950775/8229526/7baa4d6a-15d5-11e5-9dce-5c65537904d0.png)

**Comment by sporritt** [comment]
Question raised in the google group also (where it belongs)
