### ISSUE TITLE
onMaxConnections jpc isn't defined

### ISSUE THREAD

**Issue by webmull** [sporritt/jsPlumb#392]
Hi there,

I'm getting an error due to line:

https://github.com/sporritt/jsPlumb/blob/master/dist/js/dom.jsPlumb-1.7.5.js#L4618

I'm just using makeSource & makeTarget in my own implementation, but onMaxConnections never triggers because I get jpc is undefined, which from tracking the code seems to be coming from the above line.

Looking at the flow chart demo on the jsplumb site I can see it works fine, but the implementation differs as the example calls addEndPoint which I think calls maxConnections from the following:

https://github.com/sporritt/jsPlumb/blob/master/dist/js/dom.jsPlumb-1.7.5.js#L7329

is there any reason where there are two different triggers for onMaxConnections?

Cheers,
Adam

**Comment by sporritt** [comment]
did you see the comment in that code....

![image](https://cloud.githubusercontent.com/assets/262720/8242753/0adc9f9a-1655-11e5-8ea3-95af992a1eb2.png)

i think we know the answer now.

**Comment by sporritt** [comment]
would it be possible for you to supply a jsFiddle test case for this?

**Comment by webmull** [comment]
Yep I noticed the comment that's why I pointed out the code :)

I'll see if I can provide a js fiddle when I'm back at my desk tomorrow.

I was just wondering if it was anything obvious as to why the flowchart demo doesn't encounter this problem too? If I knew that I could probably work around it.

**Comment by sporritt** [comment]
sadly no...a few paths may have led to this event. i do find it maddening that I said to myself "this might be null" in that comment and neglected to supply the reason why...

**Comment by webmull** [comment]
I modified a jsFiddle made someone else and forked it to demonstrate this bug.

http://jsfiddle.net/h881rkhx/

Not the best, but it illustrates the point. Try and connect up more than 1 connection and you'll get the error. "jsPlumb function failed : ReferenceError: jpc is not defined"

Looking at the source I presume this will always happen if you call makeSource, or makeTarget? sine the only place _makeElementDropHandler is called which is where this code is via makeSource, and makeTarget - but perhaps I'm missing something?

I can see on the jsPlumb site the flowchart demo only uses addEndPoint which probably circumvents this as it get's successfully trigger via the event in: 

https://github.com/sporritt/jsPlumb/blob/master/dist/js/dom.jsPlumb-1.7.5.js#L7329

**Comment by sporritt** [comment]
Thanks for that.  This is now fixed in the 1.7.6 dev branch.

**Comment by webmull** [comment]
Thanks for that much appreciated.

Seems to work in my build.

The only thing I see now is:

jsPlumb: fire failed for event maxConnections : TypeError: Cannot read property 'attributes' of undefined

But that may be unrelated.

**Comment by webmull** [comment]
"jsPlumb: fire failed for event maxConnections : TypeError: Cannot read property 'attributes' of undefined" turns out that was a bug with my own code that was being picked up by the jsPlumb error handler.

All is working well now.

Thanks again

**Comment by sporritt** [comment]
cool, thanks for letting me know.
