### ISSUE TITLE
Mottle only defined on this in jquery jsplumb 1.7.5?

### ISSUE THREAD

**Issue by santanubasu** [sporritt/jsPlumb#393]
I only looked at it briefly due to an error I was seeing, but it looks like on line 1154 of the jquery jsplumb 1.7.5, Mottle is referenced directly, but had only been defined on this earlier.

Note that the issue appears the same way (but different line number) as far back as 1.7.2.  Just not sure how it didn't cause me problems before, so I'm wondering if I missed something when reviewing the code.

**Comment by sporritt** [comment]
closing this. it's not an issue report.  if you have a specific bug and you can provide a test case feel free to reopen.
