### ISSUE TITLE
Error in re-connecting endpoints

### ISSUE THREAD

**Issue by prahladyeri** [sporritt/jsPlumb#395]
Hi,

I'm trying to implement jsPlumb in [Visual Alchemist](https://github.com/prahladyeri/valchemist), and I'm getting this error. Scenario is:

1. A connection exists between two EPs (that represent a field in a table).
2. User modifies the table structure through a modal dialog.
3. Once user returns, I re-create the `<div>` representing the table structure on the canvas.
4. After this, I re-establish the previous connections on this table through EPs saved in a field object:

					//check incoming
					console.log('foreign key found:',key, val.ref);
					tsa = val.ref.split('.');
					fnode =tables[tsa[0]].fields[tsa[1]].ep;
					tnode = table.fields[key].ep;
					jsPlumb.connect({source: fnode, target: tnode});

And that call to `connect()` returns this error on Chrome:

    **Uncaught TypeError: Cannot read property '_jsPlumb' of undefined**

You can find this in the source code of `js\custom.js` in my repo.

Thanks,

Prahlad

**Comment by sporritt** [comment]
are you able to recreate the issue in a jsfiddle? or is the code running somewhere I can look at it?

thanks

**Comment by sporritt** [comment]
closing. two months old without replication. feel free to reopen with a test case.
