### ISSUE TITLE
Make jsPlumb run with webpack

### ISSUE THREAD

**Issue by Benvorth** [sporritt/jsPlumb#399]
I wanted to add jsPlumb to my webpack-build js-app and searched three days until I found a solution. I leave this here in case someone else is having the same issue:

1. make sure react-hot-loader is excluding the jsplumb.js lib (usually /node_modules/* is excluded so put it there)
2. require the lib with a script-loader first (to run the script once in global context)
3. and with an imports-loader second (to map this to window)

npm i --save script-loader
npm i --save imports-loader

var plumb = require('imports?this=>window!script!../node_modules/jsPlumb/dom.jsPlumb-1.7.5.js')

**Comment by sporritt** [comment]
thanks

i will put this in the documentation at some stage

**Comment by stones** [comment]
@Benvorth thanks for that. Here is the ES6 version:
import plumb from 'imports?this=>window!script!../../../node_modules/jsplumb/dist/js/jsPlumb-1.7.9.js';

You then need to refer to jsPlumb, not plumb.

**Comment by michaelmior** [comment]
Rather than mangle your import statements, you can also just use the following under `module.loaders` in your Webpack config. You can then just use `import plumb from jsplumb`. It also avoids having to mention the specific jsPlumb version.

```
      {
        test: require.resolve('jsplumb'),
        loaders: [
          'imports?this=>window',
          'script'
        ]
      }
```

**Comment by 4leem** [comment]
By using the above method to add loaders and to mange the import statement worked to resolve `Uncaught TypeError: jsPlumb.getRenderModes is not a function` error on the line `rendererTypes = jsPlumb.getRenderModes();` but I have now got another problem `Uncaught TypeError: _jsPlumb2.default.ready is not a function` __jsPlumb2.default is an empty object, it couldn't be resolved by webpack.

**Comment by sporritt** [comment]
let's call this a duplicate of #314, although of course this one happened after, and is therefore more of a etacilpud, but it's got more people chatting, so it wins. it doesnt have as good of a title as this one, but i will fix that.  i'm going to lock this one too so as to focus everybody.
