### ISSUE TITLE
Meteor package

### ISSUE THREAD

**Issue by eskan** [sporritt/jsPlumb#401]
Hello,
may you update the meteor package to the latest version ?
thanks in advance

**Comment by sporritt** [comment]
Is there a meteor package? It's not something i have created.  Where is it?

**Comment by eskan** [comment]
https://atmospherejs.com/jsplumb/jsplumb

you're right, i can't find the maintainer name :/

**Comment by sporritt** [comment]
Ah i see. Might have been a guy called Dan Dascalescu (dandv on github).

**Comment by eskan** [comment]
Thanks, i'll try to join him.
