### ISSUE TITLE
instance.makeSource doesnt't take selector as a param

### ISSUE THREAD

**Issue by woniesong92** [sporritt/jsPlumb#403]
According to the API doc, `instance.makeSource(el, params)` should take a selector string as `el`. However, it throws a `null` error. For example,

```
var el = "#my-element";
instance.makeSource(el, params); // error
el = $("#my-element");
instance.makeSource(el, params); // good
```

**Comment by sporritt** [comment]
this is a documentation misunderstanding..

![image](https://cloud.githubusercontent.com/assets/262720/8591488/f6c3ae1e-266b-11e5-9b66-ff9b8f90a059.png)

'selector' here means the result of a jQuery `$("#something")` or a `document.querySelectorAll(".someClass")` etc.

this is why the second case works for you.  leaving off the hash in the string you supply will also work.
