### ISSUE TITLE
empty function doesn't detach all connections

### ISSUE THREAD

**Issue by woniesong92** [sporritt/jsPlumb#405]
`jsPlumb.empty` function removes all elements, but doesn't remove the associated connections.

Before:
<img width="784" alt="2015-07-12 1 46 00" src="https://cloud.githubusercontent.com/assets/2935309/8637144/d04c2aa4-2837-11e5-8b36-5572fd26dc75.png">

After:
<img width="783" alt="2015-07-12 1 46 08" src="https://cloud.githubusercontent.com/assets/2935309/8637145/d51e16f0-2837-11e5-8e35-8b7dd9c72a83.png">

Similarly, `jsPlumb.detachEveryConnection();` doesn't seem to work either.

**Comment by sporritt** [comment]
is this version 1.7.5?

**Comment by woniesong92** [comment]
@sporritt Yes.

**Comment by woniesong92** [comment]
`jsPlumbInstance.detachEveryConnection()` seems to work though.

**Comment by sporritt** [comment]
@woniesong92 I wrote a unit test for this and it worked fine. then i tested in one of the demos and I didn't have a problem either. Is it possible you think `empty` does something other than what it actually does? Are you able to supply a jsFiddle?

**Comment by woniesong92** [comment]
@sporritt Can I get back to you on this? Should `empty` get rid of all the connections too, right?

**Comment by sporritt** [comment]
@woniesong92 yes it should, and that's what my unit test shows it doing.  I generally like to keep my open issue list pretty clean so i'd like to close this until you can replicate it. but by all means if you can replicate the situation open it back up.

**Comment by krunal29385** [comment]
I got the same problem,
I tried to use jsPlumb.detachEveryConnection(); but its not working
I am using jsPlumb-1.7.10.

**Comment by sporritt** [comment]
1.7.10 is not supported anymore. i suggest upgrading to the latest release.
