### ISSUE TITLE
connections render differently, when using that string representation of an achor vs that array type 

### ISSUE THREAD

**Issue by kife-design** [sporritt/jsPlumb#406]
When creating a flowchart i'm having different results when using the string representation of the anchors. When i define the anchors like the examples:

```
jsPlumbInstance.addEndpoint(el, source, {anchor: 'TopRight'});
```

my result is the following:
![schermafbeelding 2015-07-14 om 14 26 09](https://cloud.githubusercontent.com/assets/11708633/8673192/cdf30e54-2a34-11e5-95d1-b62c96e4242c.png)

Looks good. But when i define my anchors like this:

```
jsPlumbInstance.addEndpoint(el, source, {anchor: [1, 0.25, 0, 0]});
```

the result looks like this:
![schermafbeelding 2015-07-14 om 14 30 29](https://cloud.githubusercontent.com/assets/11708633/8673229/165c6384-2a35-11e5-9256-45c08fc576dd.png)

Not looking so good this time.

Is this a bug or am i missing a setting?

**Comment by sporritt** [comment]
yes, probably you want to use `[1, 0.25, 0, -1]` for that anchor.  The `-1` tells jsPlumb that the orientation of the anchor is upwards in the Y direction, which is the same as what `TopRight` uses.

**Comment by sporritt** [comment]
("yes" as in you are probably missing a setting)

**Comment by kife-design** [comment]
Ah yes, working nicely now. Ty for your help
