### ISSUE TITLE
Endpoint style cannot be transparent

### ISSUE THREAD

**Issue by Chri3y** [sporritt/jsPlumb#412]
Hi,

When I try to set the default endpoint style to be invisible, it doesn't work:

EndpointStyle: { fillStyle: "rgba(65, 169, 64, 0)", radius: 5 },

The green color is set for me, but it appears to ignore the alpha channel.

Can you help? Thank you.

**Comment by sporritt** [comment]
Yes it looks like the code actually purposefully ignores the alpha channel. There's no comment to say why this happens though. According to this page:

http://alignedleft.com/tutorials/d3/an-svg-primer

`rgba(...)` is perfectly permissible. I think I will just change this to not ignore the alpha channel.

**Comment by sporritt** [comment]
i've done this in the 1.7.7 branch now. for the SVG renderer.
