### ISSUE TITLE
Calling show on a connection after hiding it does not display it's overlay

### ISSUE THREAD

**Issue by panmari** [sporritt/jsPlumb#414]
I'm trying to hide all connections to a div by calling

    jsPlumb.hide('id_of_div')

And then showing them again with

    jsPlumb.show('id_of_div')

This works for the connection, but not for the overlay nor the custom connector. Do I have to make these show up by some different command?

Here's what I mean in two images. Before:
![selection_027](https://cloud.githubusercontent.com/assets/719020/9006754/4076f2c0-378b-11e5-82d7-2a542d13b653.png)
After calling hide() and show() again:
![selection_029](https://cloud.githubusercontent.com/assets/719020/9006757/44de3f30-378b-11e5-82df-f20003ec8a2d.png)

**Comment by sporritt** [comment]
I tried to replicate this in a unit test and in the flowchart demo but both of those worked. What versions are you using? Can you provide a jsFiddle?

**Comment by panmari** [comment]
Funny, I couldn't reproduce the behavior in jsFiddle with the most recent version. I'll try out some more stuff and report again.
My previous test was done with version 1.7.5. Could that be the issue?

**Comment by panmari** [comment]
The update fixed my issue. Thanks for your swift answer and sorry for not trying to update first.

**Comment by sporritt** [comment]
No problem...thanks for the update.
