### ISSUE TITLE
Unnecessary endpoint may be created at when drag and drop endpoint from one node to another.

### ISSUE THREAD

**Issue by ledsun** [sporritt/jsPlumb#415]
## Do below step

at [statemachine demo](https://jsplumbtoolkit.com/community/demo/statemachine/index.html).

1. Drag the target endpoint of the `con_5` and drop to the `PHONE INTERVIEW 2`.
2. Drag the source endpoint of the `con_17` and drop the `PHONE INTERVIEW 2`.

## Result
 `PHONE INTERVIEW 2` has unnecessary endpoint without a connection.

<img width="402" alt="2015-08-03 14 43 56" src="https://cloud.githubusercontent.com/assets/1079508/9031455/256bbd52-39ee-11e5-8c00-f8c291d14366.png">

## Version

This occurs in version 1.7.6.
This not occurs in version 1.7.5.

**Comment by sporritt** [comment]
this is fixed in 1.7.7 dev now
