### ISSUE TITLE
Drop Options problem

### ISSUE THREAD

**Issue by bonyjohn** [sporritt/jsPlumb#416]
I am building an application similar to Flow chart builder in jsPlumb demos
Is there a way to change dropOptions hoverClass dyamically for each node
dropOptions: {
      hoverClass: "dragHoverIncomplete"
 },

I tried to bind an over and out function. In the lastest jsPlumb 1.7.6 out function is getting called but over function is not getting triggered.

dropOptions:{ 
    over:function(e, ui) { 
      console.log("in "+e.target.id)
    },
	out:function(e, ui) { 
      console.log("out " + e.target.id)
    } 	
  }

**Comment by sporritt** [comment]
you can set `dropOptions` in each individual `makeTarget` or `addEndpoint` call, yes.

I test `out` and `over` in the flowchart demo in 1.7.8 and they seem to work fine. are you able to provide a jsfiddle showing them not working?

**Comment by sporritt** [comment]
closing....2 weeks old now without replication. feel free to reopen with a test case.
