### ISSUE TITLE
endpoints not cleaned up properly when connection converted to loopback

### ISSUE THREAD

**Issue by ledsun** [sporritt/jsPlumb#419]
This occurs at a different condition from #415.

## Do below step

at [statemachine demo](https://jsplumbtoolkit.com/community/demo/statemachine/index.html).

1. Create new edge from the `IN PERSON` to the `BEGIN`.
2. Drag the source endpoint of the `con_24` and drop the `BEGIN`.

## Result
 `BEGIN` has unnecessary endpoint without a connection.

<img width="378" alt="2015-08-12 16 26 04" src="https://cloud.githubusercontent.com/assets/1079508/9218621/dd219dfa-410e-11e5-9e43-a47da5ab12b4.png">

## Version

This occurs in version 1.7.3 - 1.7.7.

**Comment by sporritt** [comment]
original title of this:  Unnecessary endpoint may be created at when drag and drop endpoint from one node to another

i changed it so that the changelog and this are in sync.
