### ISSUE TITLE
draggable() does not for all nodes work on iOS 5.1.1

### ISSUE THREAD

**Issue by nafur** [sporritt/jsPlumb#422]
I try to use jsPlumb 1.7.6 on an iPad 1 with iOS 5.1.1.
I have the following reduced example: two nodes, both made draggable using instance.draggable().
However, only the first node that occurs in the html source is draggable, the other (all others, if there are more) are not.
A small demo can be found here: http://cipher-code.de/conceptmap/tests/draggable2.html
As far as I can see, there are no js errors in the browser. The same behaviour can be observed with Atomic Web 7.0.1 (though I'm not sure if it's a different browser or only a wrapper around Safari...)

On other browsers (chrome 43, firefox 38), everything works fine.

**Comment by nafur** [comment]
I managed to find the issue in jsPlumb/Safari and can provide a fix for it.

in function `draggable()` (around line 4115), the type of argument `el? gets checked.
If `el` is an array, `typeof el` is supposed to return `object`. Safari, however, returns `function` at this point.
Therefore, the array is detected as a single element and only the first one from the array gets handled.

To fix this, i replaced `(typeof el == 'object' && el.length)` with `((typeof el == 'object' || typeof el == 'function') && el.length)`.
I have no idea if this might have weird side effects, but it works for my case...

**Comment by sporritt** [comment]
thanks for the update. i'd need to somehow be able to set this situation up for myself to take a look; i'm a bit wary of adding that test, even though, as you say, it works for you. it's more a fear of what it might break. are you using an actual device with ios 5.1.1, or some kind of software emulation?

**Comment by nafur** [comment]
I'm using an actual iOS 5.1.1 on a physical iPad. (It's not mine though. It's a project for a friend of mine, so RTTs for tests or alike might be a bit slow ;-) ).

I fully understand your concerns. However this is such a basic thing that there may be someone somewhere who already checked how several browser behave... or did nobody ever even had the idea that some browser might screw up at this point?

**Comment by sporritt** [comment]
i'm going to close this due to the length of the time between the last activity and now, and my general reluctance to add something so fundamental. i'm not particularly upset about the latest versions of jsPlumb not supporting such an old ios version.
