### ISSUE TITLE
jsPlumb leaving nodes behind

### ISSUE THREAD

**Issue by TheMcMurder** [sporritt/jsPlumb#424]
I'm new to jsPlumb and I created this simple example. http://jsbin.com/qexiru/1/edit?html,js,output

Currently I have two dom nodes that are draggable, whenever a node is dragged to another area the circle (endpoint) is left behind. 

Am I doing something wrong or is this a bug? 

Image Added: 
![screen shot 2015-08-31 at 11 38 57](https://cloud.githubusercontent.com/assets/3059715/9585548/eca57cb8-4fd4-11e5-951b-f12f2f9c28fd.png)

**Comment by TheMcMurder** [comment]
Fixing title

**Comment by sporritt** [comment]
everything seemed spot on with this setup; it was kind of puzzling.  eventually i realised you were adding endpoints on the static instance of jsPlumb, not on the instance on which you were doing everything else:

![image](https://cloud.githubusercontent.com/assets/262720/9600761/535a9b58-50e0-11e5-9b4b-51832ec9bc8b.png)


switch those to `jsi` and it works:

![image](https://cloud.githubusercontent.com/assets/262720/9600772/60616d4a-50e0-11e5-89cd-d070a2ed9e86.png)

**Comment by TheMcMurder** [comment]
I knew I had to be doing something wrong. Thank you!
