### ISSUE TITLE
Specification of jsPlumb.on() function

### ISSUE THREAD

**Issue by vakoroteev** [sporritt/jsPlumb#425]
Looking demo examples [here](https://jsplumbtoolkit.com/demos/toolkit/spring/index.html), I'm found using of jsPlumb.on() function. There is following example of using it:
`jsPlumb.on("#main", "click", "[savelayout]", function () {});`
Where #main is id of div element, which contains jsPlumb's layout for painting graph, click is event, savelayout is attribute of button. Meaning of event and attribute is obvious, but I don't understand what value should and can take first argument (#main in example).

May be it makes sense to describe the use of this method in the documentation?

**Comment by sporritt** [comment]
done in 1.7.10, released today:

https://jsplumbtoolkit.com/community/apidocs/classes/jsPlumbInstance.html#method_on

https://jsplumbtoolkit.com/community/apidocs/classes/jsPlumbInstance.html#method_off


thanks for the suggestion!
