### ISSUE TITLE
Uuid based jsPlumb.connect() does not work

### ISSUE THREAD

**Issue by aravindakrishna** [sporritt/jsPlumb#427]
Hi,
I recently upgraded to version 1.7.10 and the connections which were made correctly before upgrading, are not happening now.
I was on 1.7.5 previously. The error I get when try to connect using the Uuids is that "Cannot establish connection - source does not exist".
Could you confirm this? Coz when I revert to 1.7.5 I don't face this error and everything works correctly.

Thanks.

**Comment by sporritt** [comment]
can you provide a code sample?

**Comment by sporritt** [comment]
...this unit test that's been in the code for a while runs fine in 1.7.10 and 2.0.0:

![image](https://cloud.githubusercontent.com/assets/262720/9717430/0a9daa7e-55b6-11e5-97a0-4a6d77b673ca.png)

**Comment by sporritt** [comment]
....this unit test still runs fine in 1.7.10 and in 2.0.0:

![image](https://cloud.githubusercontent.com/assets/262720/9717442/206c459a-55b6-11e5-85b2-e1159e950273.png)

**Comment by aravindakrishna** [comment]
I got it resolved by using scope for jsPlumb instances. Sorry for bothering you.

**Comment by sporritt** [comment]
Thanks for the update.

**Comment by dhananisangit** [comment]
@aravindakrishna can you tell mw which scope you used for solving it. Im stuck with the same problem.
