### ISSUE TITLE
RequireJS

### ISSUE THREAD

**Issue by DHoffm** [sporritt/jsPlumb#432]
Is it possible to omit the Version Name on the jsplumb file in /dist Folder. Everytime a new Version comes up I need to update my link in RequireJS.

**Comment by koppor** [comment]
See  #331 and eventually #320 for ongoing discussions.

**Comment by DHoffm** [comment]
https://github.com/sporritt/jsPlumb/issues/331
Might is the exact same request but is already closed because of.... ehm ...reasons i guess.

**Comment by sporritt** [comment]
https://github.com/jsplumb/bower-jsplumb
