### ISSUE TITLE
wrong arrow drawing (offset) when creating a connection on IE9

### ISSUE THREAD

**Issue by nicoder** [sporritt/jsPlumb#434]
hi,

We recently upgraded from 1.6.2 (with jQuery) to (vanilla) 1.7.6.

The problem we encountered is visible in your State Machine example : https://jsplumbtoolkit.com/community/demo/statemachine/index.html

Using IE9, if I click on an orange box and start moving my mouse, an arrow is drawn, but its tip is not under the cursor (as is the case in other browsers), it is positioned too much to the right and to the bottom.

It seems the more the orange box is to the right / bottom initially, the bigger the offset.

Adding jquery.jsPlumb.js seems to fix this in my project, but it did not help in the State Machine example locally.

thanks

**Comment by sporritt** [comment]
this is fixed in 2.0.5 dev
