### ISSUE TITLE
Flowchart connection: not draw full path for each endpoint

### ISSUE THREAD

**Issue by Awakening-j** [sporritt/jsPlumb#435]
Seems Flowchart only draw a full path (from source to target) for the last endpoint, not for each endpoint,  so add `HoverPaintStyle`(HoverPaintStyle: {strokeStyle: "#1e8151", lineWidth: 3 },) will only affect on the connection segment .  
Any config to draw full path for all endpoints?  
![2015-09-11 1 47 29](https://cloud.githubusercontent.com/assets/8085088/9807852/b19780a2-588b-11e5-946d-1af494b3ad96.png)
![2015-09-11 1 47 37](https://cloud.githubusercontent.com/assets/8085088/9807854/b34504f6-588b-11e5-8f3a-f1a56d5b5d3f.png)

**Comment by sporritt** [comment]
this is a z-index issue. you need to set a z-index for the hovered connection to be above the others.

https://jsplumbtoolkit.com/community/doc/styling-via-css.html

you might have

`_jsPlumb_connector { z-index:5; }`

and then 
`_jsPlumb_hover { z-index:6; }`

note that in 2.0.0 (to be released soon) these classes will be `jsplumb-connector` and `jsplumb-hover`.

**Comment by Awakening-j** [comment]
@sporritt Thank you

**Comment by Awakening-j** [comment]
@sporritt one more question, how can I find related connector when hover/click an endpoint, I want to add highlight css to the connector

**Comment by sporritt** [comment]
If you've got an Endpoint you can access its connections via the 'connections' array (`someEndpoint.connections`)

**Comment by Awakening-j** [comment]
I didn't use `addEndpoint`, but using simple div, then do `jsp.connect`, and when I call `jsp.getEndpoint(id)`  it returns undefind. Is it the right result?  Or I must do as `addEndpoint`

**Comment by Awakening-j** [comment]
@sporritt could you show me a demo how to highlight connection when hover target? I've tried to get the connections by `jsp.getAllConnections()`, but not find a way to set `hover-class` for the connection

**Comment by Awakening-j** [comment]
@sporritt hi?are you here?

**Comment by sporritt** [comment]
When you hover the target or source of a connection that connection is assigned the `jsplumb-hover` class. see [this page](https://jsplumbtoolkit.com/community/doc/styling-via-css.html) for a full list of css class assignments.
