### ISSUE TITLE
Remove version number from file name

### ISSUE THREAD

**Issue by jpmckearin** [sporritt/jsPlumb#436]
Please remove the version number from the jsplumb file name. This is horrible practice and makes it a pain in the butt to update references.

**Comment by sporritt** [comment]
( #432  #320  #331 )

**Comment by jpmckearin** [comment]
Sorry to just create an issue without even searching for existing ones. One can say I was "extremely frustrated." Looking forward to seeing #426 being merged.

**Comment by sporritt** [comment]
https://github.com/jsplumb/bower-jsplumb
