### ISSUE TITLE
Strange `this` context behavior in Katavorio.select function

### ISSUE THREAD

**Issue by payne8** [sporritt/jsPlumb#439]
Hey we are using jsPlumb in production. This is a great library, thanks for providing it.

I ran into a very strange issue that is difficult to explain. We concatenate all our libraries into our application when in production. In development using addToDragSelection works great to allow dragging of multiple elements. As soon as we concat jsplumb into the rest of our code addToDragSelection stops working as expected. 

In the current 1.7.10 version the Katavorio.select function (around line 1886) we see this:

```
this.select = function(el) {
  _each(el, function() {
    var _el = _gel(this);
    if (_el && _el._katavorioDrag) {
      if (!_selectionMap[_el._katavorio]) {
        _selection.push(_el._katavorioDrag);
        _selectionMap[_el._katavorio] = [ _el, _selection.length - 1 ];
        katavorioParams.addClass(_el, _css.selected);
      }
    }
  });
  return this;
};
```

The _each function calls the callback with a fn.apply(obj[i], [ obj[i] ]); so the value of `this` should be the same as the first value of the arguments.

The line where it calls _gel(this) has different behavior in different environments. On an empty html page if you run something like this:

```
var testFn = function(){console.log(this);};
testFn.apply('This is a string');
```

This logs an object of type String rather than a primitive string. The _gel function is expecting a primitive string not a String object. In order to resolve this odd and inconsistent behavior I changed the callback in the _each function to use the first argument passed as the parameter for the _gel function. Here is the function as it stands on our production code.

```
this.select = function(el) {
    _each(el, function(ek) {
        var _el = _gel(ek);
        if (_el && _el._katavorioDrag) {
            if (!_selectionMap[_el._katavorio]) {
                _selection.push(_el._katavorioDrag);
                _selectionMap[_el._katavorio] = [ _el, _selection.length - 1 ];
                katavorioParams.addClass(_el, _css.selected);
            }
        }
    });
    return this;
};
```

That small change fixed our issue. There may be other places in the code the use the `this` context rather than an argument. I figure most of the time this wouldn't be an issue. It was an issue for us in production and wanted to highlight the problem.

Thanks again for a great library!

**Comment by sporritt** [comment]
@payne8  thanks for this.  i was able to recreate this in a unit test in Katavorio. I didn't put this specific fix in; i added a check wherever it was testing for string to also check for object String:

https://github.com/jsplumb/katavorio/commit/3234a03ba4602dace739eea2223378bd63266d3f

Katavorio 0.9.0 is going in to jsPlumb 2.0.0, which I am releasing very soon.
