### ISSUE TITLE
connectionDetached fired when beforeDrop returns false

### ISSUE THREAD

**Issue by cneuro** [sporritt/jsPlumb#440]
I would've thought that returning `false` from an Endpoint's `beforeDrop` handler would not fire any subsequent events, since a Connection was never made. However, jsPlumb's `connectionDetached` is still fired for that element. This persists in v1.7.10

Is this intended? It makes events handling a chore if the global`connectionDetached` callback also needs to know in what case it was fired.

```javascript
jsPlumb.instance.addEndpoint(someElement, {
  'beforeDrop': function (info) {
    if (someCase) {
      // connection is invalid
      return false;
    }
   // connection is valid
   return true;
  }
});

jsPlumb.instance.bind('connectionDetached', function (info) {
  // this is fired even when beforeDrop returns false (i.e. cancelling the attempted connection)
});
```

**Comment by sporritt** [comment]
No, I don't think that is intended.  I'll write up a test case and try to replicate.

**Comment by sporritt** [comment]
this is fixed in 2.0.0 dev

**Comment by cneuro** [comment]
amazing! thanks for your work and this great project. Cheers :)

**Comment by cneuro** [comment]
The `connectionDetached` event is *also* fired when `onMaxConnections` is defined on an Endpoint.

````javascript
jsPlumb.instance.addEndpoint(someElement, {
  'onMaxConnections': function (info) {
    // this shouldn't subsequently bubble up to the instance's connectionDetached callback
    return false;  // does not prevent the propagation
  }
});
```

Is this by design? In my understanding a Connection is only "detached" if it already exists. Under both of the cases listed in this issue, the Connection shouldn't have logically existed yet for it to call a detach event.

**Comment by sporritt** [comment]
onMaxConnections is not an interceptor. It's just an event telling you something happened.
