### ISSUE TITLE
Improvement of documentation for method connect (fireEvent param)

### ISSUE THREAD

**Issue by vakoroteev** [sporritt/jsPlumb#445]
Parameter `fireEvent` is missing in params description but it exists.
https://jsplumbtoolkit.com/community/apidocs/classes/jsPlumbInstance.html#method_connect

**Comment by sporritt** [comment]
yes, but it isn't part of the public API.

**Comment by vakoroteev** [comment]
Oh, this confused me a bit, because the parameter `fireEvent` exists in description of method `detach`, and I think that this parameter is equivalent for both methods.
https://jsplumbtoolkit.com/community/apidocs/classes/jsPlumbInstance.html#method_detach

**Comment by sporritt** [comment]
it is equivalent, true. i think in fact it should not be described anywhere.

**Comment by sporritt** [comment]
i took a look at the api docs for detach. They explain the inclusion of `fireEvent` like this:

```
Indicates you want jsPlumb to fire a connection detached event. The thinking behind this is that if you made a programmatic call to detach an event, you probably don't need the callback.
```

then i looked at `connect` - it doesn't actually have a `fireEvent` parameter.  closing this out.

**Comment by lizardoluis** [comment]
I didn't understand. `fireEvent` was removed from `connect` on the Community Edition?
