### ISSUE TITLE
Why "connection.scope" property cannot get scope value ?

### ISSUE THREAD

**Issue by HiroyukiKitada** [sporritt/jsPlumb#452]
Hi,
 Why "connection.scope" property cannot get scope value ?

https://jsplumbtoolkit.com/community/demo/draggableConnectors/

 It works on version 1.7.2.
 
 Thanks.

**Comment by dbnoble** [comment]
https://github.com/sporritt/jsPlumb/issues/469

**Comment by sporritt** [comment]
fixed in 2.0.6 dev
