### ISSUE TITLE
Maximum dimension of grid is limited to 10px.

### ISSUE THREAD

**Issue by dmytro6** [sporritt/jsPlumb#453]
If you set griddable drag & drop in jsPlumb it works correct only if grid dimension is no bigger than 10 pixels. If it's bigger - grid doesn't works. Can you change it? Have reproduced this using jsPlumb version 2.1.0. In library code have found that it can be fixed by increasing "snapThreshold" value on line 1410.

**Comment by sporritt** [comment]
closing this out from here. need to track it, preferably with a test case, in the Katavorio project.
