### ISSUE TITLE
connectionDetached is fired the first time only

### ISSUE THREAD

**Issue by Malraoosh** [sporritt/jsPlumb#458]
After the first manual detach connection, if I detach another one (drag connection line from end point and drop on empty area) I get this error:

    jsPlumb: fire failed for event connectionDetached : TypeError: Cannot read property 'length' of undefined

I have version 2.0.4, is this a bug?

**Comment by sporritt** [comment]
yes this was an issue; i believe it was fixed as part of some other work. i cannot reproduce it in either the flowchart or state machine demos in dev right now. marking closed, but feel free to reopen if you think differently.

**Comment by Malraoosh** [comment]
Can you please show me where is the original issue of this bug?

**Comment by sporritt** [comment]
no, i can't.  it wasn't tracked through an issue in the community version.

**Comment by Malraoosh** [comment]
ok, how would I help you to re-produce the bug at your side?

**Comment by sporritt** [comment]
if you want to verify if it is fixed you can download 2.0.5, which i just released, and try to replicate the issue you were having.

**Comment by Malraoosh** [comment]
ok, i will try, thanks.

**Comment by ducwings** [comment]
Hi, with the latest version, I'm getting a similar error:
"jsPlumb: fire failed for event connectionDetached : RangeError: Maximum call stack size exceeded
jsPlumb: fire failed for event connectionDetached : TypeError: Cannot read property '1' of null"
(infinite loop occurred for this log)
by calling: jspInstance.detachEveryConnection()

**Comment by sporritt** [comment]
maybe you can post a jsfiddle or something.  if you go here:

https://jsplumbtoolkit.com/community/demo/flowchart/index.html

and open up the console and type

`jsp.detachEveryConnection()`

there is no problem.
