### ISSUE TITLE
Parameters key case consistency

### ISSUE THREAD

**Issue by Toilal** [sporritt/jsPlumb#461]
Is there any reason for parameters keys to be UpperCased in [jsplumb.importDefaults()](https://jsplumbtoolkit.com/community/doc/defaults.html), but camelCased in [jsplumb.connect()](https://jsplumbtoolkit.com/community/doc/connect-examples.html) ?

It seems quite confusing to me ...

Anyway thanks for this library, it do the job !

**Comment by sporritt** [comment]
not really. the burden of history, basically. it bothers me too. maybe for version 2.1.0 (which might be the next one), i can use the minor version bump as an excuse to change that...it's not backwards compatible of course.

**Comment by sporritt** [comment]
history wins.  this issue does not.
