### ISSUE TITLE
Remove version number from build output

### ISSUE THREAD

**Issue by peterhodges** [sporritt/jsPlumb#462]
The dist files for jsPlumb have the version number appended to them (e.g. jsPlumb-2.0.5.js).

This makes it really clunky to use bower to switch between versions because you have to update the version number in bower.json, run bower install and then update your app to point at the correct js file. 

I would suggest the version number is removed from the dist files or that a second set of unversioned files are included and that bower.json points to these using the main property instead.

**Comment by enapupe** [comment]
There is another issue about this: https://github.com/sporritt/jsPlumb/issues/331

**Comment by sporritt** [comment]
My thoughts on this are pretty clear in the issue linked to above, and others. I won't be removing the version number from the filename. The best solution seemed to be the one that other projects do, which is to have a separate "**-bower" repository to cater for bower's inherent weaknesses.

**Comment by PhiLhoSoft** [comment]
The problem would be the same with `npm install,` no? You still have to update the index file including the jsPlumb JS file each time we get a new version. Something we don't have to do with all the other libraries we use.

**Comment by sporritt** [comment]
https://github.com/jsplumb/bower-jsplumb
