### ISSUE TITLE
Missing images with bower install

### ISSUE THREAD

**Issue by kviktor** [sporritt/jsPlumb#465]
When installing with bower there are no images (img folder), is this a feature or a bug?

**Comment by sporritt** [comment]
the only thing installed is the built js file. that's all jsplumb needs.

**Comment by sporritt** [comment]
...or rather, i should say, the only thing in the `main` declaration of `bower.json` is the built js file. i dont know what bower actually does; i haven't installed jsplumb via bower myself.

**Comment by kviktor** [comment]
My problem is that the CSS that comes with bower install have a reference for a `back-green.jpg` which is not downloaded.

**Comment by sporritt** [comment]
Css is installed by bower? The bower json declares only a js file.

**Comment by kviktor** [comment]
```
$ bower install jsPlumb
$ find . | grep css
./bower_components/jsPlumb/dist/css
./bower_components/jsPlumb/dist/css/ico-jsplumb.svg
./bower_components/jsPlumb/dist/css/main.css
./bower_components/jsPlumb/dist/css/jsPlumbToolkit-demo.css
./bower_components/jsPlumb/dist/css/ico-jsplumb.woff
./bower_components/jsPlumb/dist/css/ico-jsplumb.ttf
./bower_components/jsPlumb/dist/css/jsplumb.css
./bower_components/jsPlumb/dist/css/external
./bower_components/jsPlumb/dist/css/external/cssgrids-min.css
./bower_components/jsPlumb/dist/css/external/prettify-min.css
./bower_components/jsPlumb/dist/css/ico-jsplumb.eot
./bower_components/jsPlumb/dist/css/jsplumb-doc.css
./bower_components/jsPlumb/dist/css/jsPlumbToolkit-defaults.css
./bower_components/jsPlumb/css
./bower_components/jsPlumb/css/ico-jsplumb.svg
./bower_components/jsPlumb/css/main.css
./bower_components/jsPlumb/css/jsPlumbToolkit-demo.css
./bower_components/jsPlumb/css/ico-jsplumb.woff
./bower_components/jsPlumb/css/ico-jsplumb.ttf
./bower_components/jsPlumb/css/jsplumb.css
./bower_components/jsPlumb/css/external
./bower_components/jsPlumb/css/external/cssgrids-min.css
./bower_components/jsPlumb/css/external/prettify-min.css
./bower_components/jsPlumb/css/ico-jsplumb.eot
./bower_components/jsPlumb/css/jsplumb-doc.css
./bower_components/jsPlumb/css/jsPlumbToolkit-defaults.css
```

**Comment by sporritt** [comment]
yep

one again bower does a fine job of mistaking itself for a source control system.

then to answer your initial question - it's a feature.  if you want the whole repo, clone it.

**Comment by kviktor** [comment]
Okay, I'll close this issue then.

(tho fixing the bower.json to either only add the JS file or css with images would be good)

**Comment by sporritt** [comment]
do you know how to do that? because that is what i thought it was setup to do. you dont need the css. you just need the js file.
