### ISSUE TITLE
'isSourceEnabled' do not work on ver > 2.0.x

### ISSUE THREAD

**Issue by daskyrk** [sporritt/jsPlumb#466]
in the demo 'statemachine',when i add the **instance.isSourceEnabled(el.id)** in function initNode as below:
```
instance.makeTarget(el, {
            dropOptions: { hoverClass: "dragHover" },
            anchor: "Continuous",
            allowLoopback: true
});
console.log(instance.isSourceEnabled(el.id));//undefined
console.log(instance.isTargetEnabled(el.id));//true
```
**function isSourceEnabled() will return undefined**.
i tried in version > 2.0.2,it'a all the same result.But on the version 1.7.8,it will work rightly.

**Comment by daskyrk** [comment]
after reading the source code,i find that the problem seem to begin from the attr **connectionType**,
```
instance.makeSource(el, {
    filter: ".ep",
    anchor: "Continuous",
    connectorStyle: { strokeStyle: "#5c96bc", lineWidth: 2, outlineColor: "transparent", outlineWidth: 4 },
    connectionType:"default",//change here from 'basic' to default
    extract:{
        "action":"the-action"
    },
    maxConnections: 2,
    onMaxConnections: function (info, e) {
        alert("Maximum connections (" + info.maxConnections + ") reached");
    }
});
```
**when i change connectionType to 'default',it can work.**
but it means we can't rename the connectionType,it may have a defect here？

**Comment by sporritt** [comment]
this was raised again recently in #517 

the method signature for both `setSourceEnabled` and `isSourceEnabled` now take a `connectionType` parameter:


```
this.setSourceEnabled = function (el, state, connectionType) {

}
```

```
this.isSourceEnabled = function (el, connectionType) {

}
```

this can't be changed.  you will have set a type if you want to use these methods.
