### ISSUE TITLE
Scopes not applied to new drag & drop connections (fix included)

### ISSUE THREAD

**Issue by dbnoble** [sporritt/jsPlumb#469]
@sporritt - Scopes for draggable connections have been broken for some time now. Unless there was some specific, intentional reason this stopped working, it's a very easy fix.

Example: https://jsplumbtoolkit.com/community/demo/draggableConnectors/ should reflect scopes `blue`, `yellow`, and `green`, however they all return `jsPlumb_DefaultScope` instead.

This block in endpoint.js is the culprit, the scope is not being passed in from `params`. We need to add `scope: params.scope` to the object for it to work again.
````
jpc = _newConnection({
                            sourceEndpoint: this,
                            targetEndpoint: this._jsPlumb.floatingEndpoint,
                            source: this.element,  // for makeSource with parent option.  ensure source element is represented correctly.
                            target: placeholderInfo.element,
                            anchors: [ this.anchor, this._jsPlumb.floatingEndpoint.anchor ],
                            paintStyle: params.connectorStyle, // this can be null. Connection will use the default.
                            hoverPaintStyle: params.connectorHoverStyle,
                            connector: params.connector, // this can also be null. Connection will use the default.
                            overlays: params.connectorOverlays,
                            type: this.connectionType,
                            cssClass: this.connectorClass,
                            hoverClass: this.connectorHoverClass,
                            data:beforeDrag
                        });
````

Here is the exact location: https://github.com/sporritt/jsPlumb/blob/master/src/endpoint.js#L593-L607

If you'd like a pull request let me know.

**Comment by sporritt** [comment]
thanks, i will take a look at this shortly.

**Comment by sporritt** [comment]
fixed. i had to add it in another place too for the programmatic `connect(...)` call. thanks.
