### ISSUE TITLE
Auto deploy from Bower to WebJar repo

### ISSUE THREAD

**Issue by bpervan** [sporritt/jsPlumb#470]
Hi,

I tried to deploy jsPlumb from Bower to WebJar repo using http://www.webjars.org/bower The process failed with: "Failed! /tmp/git1307232102632937173/git:/github.com/sporritt/jsPlumb.git/MIT/GPL2 (No such file or directory)"

I filed an issue to WebJar main repo, and, as one of the developers stated, the auto deploy failed due to the incorect form of the metadata for the licence (see webjars/webjars#1301)

Can we work this out somehow? I think it would be pretty nice to have this kind of 'feature' enabled for jsPlumb.

Cheers,
Branimir

EDIT: Of course there is an option to use already deployed non-bower WebJar, but I think this would be more convenient, as it requires no WebJar devs effort to upgrade to newer versions of jsPlumb. What I think that bothers WebJar auto deployment system is dual licence in bower.json ("licence": "MIT/GPL2")

**Comment by sporritt** [comment]
it is dual licensed though. what do they think about that?

**Comment by bpervan** [comment]
Dunno, answer on webjars/webjars#1301 sounds like he has no intention of making WebJar auto deployment system to process dual licensed bower packages.

**Comment by sporritt** [comment]
yes he seems quite definitive.

**Comment by bpervan** [comment]
I'm really not into that legal/license stuff (for now). Would it be possible to declare only one, more permissive (GPL2) licence in bower.json? MIT licence would still stay included in all copies and wherever necessary? Am I allowed to make a fork and publish it to bower repo under some kind of a subname (jsplumb-webjar for example)?

**Comment by sporritt** [comment]
the solution would appear to be that the `license` entry in bower.json pointed to a document in which it was stated that jsplumb is dual licensed. webjars is reading the existing entry according to bower's rules, which is that you either name the license with an SPDX name, or use a path to a file.  And since there's a slash in jsPlumb's entry, it thinks its a path.

**Comment by bpervan** [comment]
sporritt/jsPlumb/471

**Comment by sporritt** [comment]
looks good, thanks. merged.
