### ISSUE TITLE
Pending connections do not fire the documented events

### ISSUE THREAD

**Issue by dbnoble** [sporritt/jsPlumb#472]
From the documentation on `connectionDetached(info, originalEvent)`:

>In the event that the Connection was new and had never been established between two Endpoints, it has a pending flag set on it.

This is actually not true - the event does not fire at all in that case. I believe that changed as a result of modifications made in reference to https://github.com/sporritt/jsPlumb/issues/440

Here is a working example that shows the result of the different handlers and a lastEvent tracker: 
http://codepen.io/vertical3/pen/GoQRXK

You'll notice that abandoning the connection results in the "DRAGGING" status not being cleared by `connectionDetached`. Detaching from an existing connection works as expected.

Instead, you have to use `connectionDragStop`, which fires *anytime* you release an endpoint, even when a connection is made (after the `connection` event, in fact). This is where you can intercept an abandoned connection by checking that `connection.pending == true`. 

I'm not saying that this is a problem necessarily, just that either the documentation is wrong or the code is not working as intended, depending on which you favor. I don't think that having to use connectionDragStop is ideal since it fires so often, but other than that it's fine.

**Comment by sporritt** [comment]
i think i prefer it to not fire `connectionDetached` if there was never really a connection. 

Can you clarify what you mean by "You'll notice that abandoning the connection results in the "DRAGGING" status not being cleared by connectionDetached".  I never see a `connectionDetached` event reported, even when dragging an existing connection.

maybe it would be good to have a `connectionAborted` event for this case.

**Comment by sporritt** [comment]
in 2.0.6 dev the docs are updated to be correct, and there is a `connectionAborted` event that is fired whenever a connection is abandoned before being dropped on an endpoint or target. it is also fired in the event that a `beforeDrop` interceptor returns false.

**Comment by dbnoble** [comment]
@sporritt 
Awesome! Yes I was thinking a `connectionAborted` event was better fitting.

The reason never saw the `connectionDetached` on existing connections on my example is because `connectionDragStop` always gets fired immediately after and the event-tracker was made in such a way that it only showed the LAST event. That is why I made a way to disable the output handler for the `connectionDragStop` so you that it was apparent that when you abanoned the connection, it was not firing the connectionDetached handler as implied in the docs, and the connection status would still show "DRAGGING".

In retrospect, I should have used a scrolling window for the tracker to make things more clear.

**Comment by sporritt** [comment]
Cool. Well 2.0.6 is released now. Give it a try and if you need anything else by all means reopen the issue.
