### ISSUE TITLE
Array.prototype.suggest & Array.prototype.vanquish

### ISSUE THREAD

**Issue by marcstee** [sporritt/jsPlumb#480]
jsPlumb adds to Array.prototype 2 new methods which by that are added to all Arrays on the site where jsPlumb is used and it makes some problems.

I.e.: going through any array in for() makes 2 additional loops.

**Comment by sporritt** [comment]
this was fixed a few versions ago. it was in Katavorio, the drag library, changed to a helper function in v 0.13.0.
