### ISSUE TITLE
Repaint on scrolled down page.

### ISSUE THREAD

**Issue by Nenos-Hu** [sporritt/jsPlumb#481]
Hello,

I have an issue while repainting on a scrolled down page.

Good display : 
![image](https://cloud.githubusercontent.com/assets/16306211/12921353/3321b196-cf4d-11e5-89bc-335cbcc8e1b9.png)

Display when I repaintEverything on a scolled down page :
![image](https://cloud.githubusercontent.com/assets/16306211/12921399/721fd332-cf4d-11e5-9b64-b92aacf87cc8.png)

I'm using v2.0.7.

I didn't find where the issue comes from.
Am I doing something wrong ?

Thanks in advance.

Nenos

**Comment by tangoda** [comment]
`$(window).resize(function () { jsPlumb.repaintEverything(); });`

**Comment by sporritt** [comment]
it looks like you may not have set an appropriate Container:

https://jsplumbtoolkit.com/community/doc/home.html#container

**Comment by Nenos-Hu** [comment]
That's it !
Thank you ! :)
