### ISSUE TITLE
TypeError: e.srcElement is undefined in "State Machine" Demo

### ISSUE THREAD

**Issue by SimonEbner** [sporritt/jsPlumb#483]
Hi,

I cannot create connections in the demo "State Machine" (https://jsplumbtoolkit.com/community/demo/statemachine/index.html).
Whenenver I try to drag the handle, I get the error "e.srcElement" is undefined in line 5256 (var v = e.srcElement.getAttribute(att)).
I'm running firefox 39.0 under ubuntu 14.10

Changing e.srcElement by e.target (as suggested by http://stackoverflow.com/questions/13602039/e-srcelement-is-undefined-in-firefox) seems to solve the problem for me in firefox.

**Comment by sporritt** [comment]
thanks.  you can't trust `target` in IE, older IE in particular. i dont know how this one slipped through the net but generally in the jsPlumb code you'll see `(e.srcElement || e.target)`.  this is fixed in 2.1.0 dev.
