### ISSUE TITLE
Iligal variable names used on two places in the code.

### ISSUE THREAD

**Issue by Tenerezza** [sporritt/jsPlumb#484]
The issue exist on line 4673 in jsPlumb-2.0.7.js

the variable name transient is not valid.

Same goes for line 12570
int is as well not a valid variable name.

Reason is that some Javascript compressors, in my case (Yahoo's) one fail to compress this project, personally not sure how to contribute code to this project

**Comment by sporritt** [comment]
these are fixed in 2.1.0 dev
