### ISSUE TITLE
Update label overlay when edited via contenteditable

### ISSUE THREAD

**Issue by chipsenkbeil** [sporritt/jsPlumb#489]
Trying to figure out the best way to update a label overlay that is edited with contenteditable="true". First thought is to get the updated value from a blur event and set the label content with the DOM's value. Does this sound like a valid plan? Does jsPlumb have something better available?

**Comment by sporritt** [comment]
There is nothing in the api for this. I would probably start with that approach and see if it flies.

**Comment by chipsenkbeil** [comment]
Works just fine. :)
