### ISSUE TITLE
How to get the layout on the serverside

### ISSUE THREAD

**Issue by patagoniahiker** [sporritt/jsPlumb#491]
Hi, I am interested in your toolkit, I saw a demo for the flow chart. But there is no explanation on 

1. Does it have hierarchical and workflow
2. Layout-detection or creation.
3. Are the HTML nodes customizable.
4. How does the user persist the state to the server, are there calls built into the lib to do so?

thanks

**Comment by sporritt** [comment]
hello

this github repo is the community edition, which had none of the things you ask about above.  to answer your questions:

1. Hierarchical, yes. "Workflow" no, but you could use the Absolute layout for that.
2. Detection - not sure what you mean. Creation - again not sure. You can create your own custom layouts.
3. Yes, completely. You write client side templates and use html/css to style.
4. there is an 'auto save' function or you can use the export method yourself and do it manually.

**Comment by patagoniahiker** [comment]
Ok thanks. I just saw your commercial pricing, any cheaper options for developers.

**Comment by sporritt** [comment]
Ah...no. developes ARE the people the Toolkit is intended for.
