### ISSUE TITLE
Autoscroll on Drag

### ISSUE THREAD

**Issue by paulsen-it** [sporritt/jsPlumb#492]
I had the Problem that I can not scroll when I Drag. I have insert some Code. If you want, you can use it.
[jsPlumb-2.0.7.js.zip](https://github.com/sporritt/jsPlumb/files/187980/jsPlumb-2.0.7.js.zip)

A complete description of the Problem and Solution you can found on google Groups
https://groups.google.com/forum/?fromgroups=#!topic/jsplumb/XTHBVl8ZfOg

I don't test all thinks. For Example I don't use Zoom. And I have a Problem to get the Offset of the Container. See Comments in Script. I hope you have a better solution. 

Thank you for jsPlumb! This is a very nice Library.

**Comment by sporritt** [comment]
thanks. we'll review this at some stage when we get to this feature (but it will be added to Katavorio, not jsPlumb).
