### ISSUE TITLE
connect to circle shape, how to adjust arrow position

### ISSUE THREAD

**Issue by Awakening-j** [sporritt/jsPlumb#493]
I'm working on a topology graph with circle shape, how to adjust arrow position when draging  
Case 1:  
  when I set `anchor: ['Center']`, and set element style `z-index: 10; background:white`, then the arrow will be covered, and I don't know how to move it few px away from the `target`.  
Case 2:  
  then I set `anchor: ['TopLeft']` or other, the arrow line will display right only in one drection, see screenshots  
![2016-03-28 16 33 50](https://cloud.githubusercontent.com/assets/8085088/14074452/93f3b4a2-f503-11e5-8757-6c95195811f7.png)
![2016-03-28 16 33 54](https://cloud.githubusercontent.com/assets/8085088/14074453/93fc1688-f503-11e5-836c-f9adcc51e82b.png)
![2016-03-28 16 34 47](https://cloud.githubusercontent.com/assets/8085088/14074454/93fd0728-f503-11e5-910e-b1b58d354183.png)

As shown in the png, the left target arrow line not show right,  
So how to adjust arrow line for a dragable circle shape?  
Or how to move arrow a little far from the target element  

Thanks

**Comment by sporritt** [comment]
have you seen [this demo](https://jsplumbtoolkit.com/community/demo/perimeterAnchors/index.html) ?

**Comment by Awakening-j** [comment]
@sporritt thanks. sorry, my fault

**Comment by Awakening-j** [comment]
@sporritt BTW, how to draw a dashed straight line? I'm confused with the [doc](https://jsplumbtoolkit.com/community/doc/paint-styles.html) about dashstyle

**Comment by sporritt** [comment]
closing this since you have opened yet another issue for this

**Comment by Awakening-j** [comment]
@sporritt Thanks, I may not catch your point about dash
