### ISSUE TITLE
SVGElement.offsetWidth deprecated soon in Chrome

### ISSUE THREAD

**Issue by sporritt** [sporritt/jsPlumb#494]
SVGElement.offsetWidth' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.

**Comment by 304NotModified** [comment]
It looks like this gives already issues now with Chome 49 :(

**Comment by sporritt** [comment]
what do you mean? it breaks?

**Comment by sporritt** [comment]
@304NotModified could you give me a little more context about your setup? are you trying to connect two svg elements?

**Comment by sporritt** [comment]
and are you on windows?  i cannot reproduce this in chrome on any platform right now.

**Comment by 304NotModified** [comment]
Hi! We have tested this again, and we were wrong. This issue was suddenly, and related to the offset, but it wasn't this issue. 

Sorry about the confusion.
