### ISSUE TITLE
Ability to nest Groups inside other Groups

### ISSUE THREAD

**Issue by sporritt** [sporritt/jsPlumb#503]
There should be an `addNestedGroup` method:

```
jsPlumb.addNestedGroup(toGroupOrGroupId, element, groupId, params)
```

Connections and dragging should behave exactly the same in a nested group as all other Groups. The "only" complications come from the collapse action. A few points on this (probably not exhaustive):

- If a Group containing Nested Groups is collapsed, then Connections from those Nested Groups to Nodes/Groups outside of the collapsed Group must all be proxied to the collapsed Group's container, not to their own Container.

- If a Nested Group is instructed to collapse or expand but it is inside a collapsed Group, it should expand or collapse but not change any Connections.

- If a collapsed parent Group has a child Group whose collapsed state has changed since it was collapsed, there are complications that need to be taken into account when reassigning proxied Connections.

- If a user deletes a proxy Connection (ie. a Connection to a collapsed Group) we'll need to update the code to check which, if any, Nested Group the Connection belongs to.

**Comment by sporritt** [comment]
- nested Group IDs are expected to be unique to the entire jsPlumb instance, not just to their parent Group

**Comment by sporritt** [comment]
descoped.

**Comment by dzza** [comment]
Hi and thanks for this library. 

Is this anywhere on the roadmap? Toolkit?

**Comment by sporritt** [comment]
it's vaguely on the roadmap, yes. it wouldn't be toolkit only, we'd probably put it in the community edition.

**Comment by dzza** [comment]
Awesome! Any temporary workaround to achieve this or is it currently technically impossible ?

**Comment by nguyenvanbac1988** [comment]
sporritt : did you have any progress in this issue , 
thanks

**Comment by sporritt** [comment]
not yet.

**Comment by websitewill** [comment]
How about yet? Just ran into this disappointing line of code in the js when trying to figure out why I can't nest groups.
if (el._isJsPlumbGroup) {
    return;
}

I am assuming this is still an issue? What would it take to get it implemented?

**Comment by sporritt** [comment]
yes i can see how you'd find that line of code disappointing, if you're looking to nest groups.  No movement on this yet. Still vaguely on the roadmap, without any fixed date. At this point it would be something that was added to the 4.x branch.

To me this still sounds like something that could turn into a hot mess visually. But without playing around with a prototype i may just be saying pointless words.

**Comment by websitewill** [comment]
I don't necessarily see it as being any different than an element with a hundred connections of it's own.
When you collapse a group, calculate the proxy locations as normal but force all grandchild connections or lower to also use one of those proxy locations. That or just treat each connection as if it comes from the direct center of the collapsed grandparent but leave the rest of the logic alone?

I'm in no way a JS guy so maybe this isn't as easy as I am trying to reason it out to be?

**Comment by nguyenvanbac1988** [comment]
> I don't necessarily see it as being any different than an element with a hundred connections of it's own.
> When you collapse a group, calculate the proxy locations as normal but force all grandchild connections or lower to also use one of those proxy locations. That or just treat each connection as if it comes from the direct center of the collapsed grandparent but leave the rest of the logic alone?
> 
> I'm in no way a JS guy so maybe this isn't as easy as I am trying to reason it out to be?

i did it myself for my projects, but i admit that there is some issue of performances, but if you don't use too much port feature and  your canvas get it less than 100 nodes, i can give some suggestion

**Comment by sporritt** [comment]
to be clear, i wasnt really commenting on the complexity of the task from a code perspective. i was thinking out loud about how easy it would be for the ui to become a hot mess.
