### ISSUE TITLE
How to write a dashed connector

### ISSUE THREAD

**Issue by Awakening-j** [sporritt/jsPlumb#504]
How to write a dashed connector?  
Is there any example of `dashstyle` ?

**Comment by sporritt** [comment]
you already had an issue opened for this

would you mind not flooding our issue list with questions. this is not even a bug report or an enhancement request. we have a google group where people can ask questions.

**Comment by sporritt** [comment]
plus, there is a dashstyle example in the demo to which i pointed you in answer to your original question.

https://jsplumbtoolkit.com/community/demo/perimeterAnchors/app.js
