### ISSUE TITLE
Drag container

### ISSUE THREAD

**Issue by vicky626** [sporritt/jsPlumb#512]
Is there ways to drag container? I want to drag the whole container when keypress not on the Element.  
I try to 
```
instance.draggable instance.getContainer()
```  
But seems not drag correct

**Comment by sporritt** [comment]
would you mind using the google group for questions. this is the second issue you have raised that is neither a bug report nor an enhancement request.

**Comment by sporritt** [comment]
(to answer your question, there is nothing stopping you from making the container draggable. but this is not specifically a jsplumb question, since jsplumb exists inside of that container. where you position it on the screen, and how, has got nothing to do with jsplumb)
