### ISSUE TITLE
how to programmatically connect draggable endpoints together??

### ISSUE THREAD

**Issue by juanbill** [sporritt/jsPlumb#519]
Hi:

I have setup draggable endpoints with my elements and are able to create connections with drag and drop operations. 

I would like to programmatically connect some of them. I tried instance.connect({source:element, target:element}), but it doesn't carry over the styles which I have already setup for the draggable endpoints, and it seems instance.connect is creating a new set of dom elements instead of reusing the ones I've already made.

Is there a way to programmatically connect my elements with drag and drop endpoints? 

Thanks

**Comment by sporritt** [comment]
Look at the flowchart demo. You pass in the Endpoint objects that are returned from an addEndpoint call as source and target.
