### ISSUE TITLE
endpointDblClick doesn't fire, click fires 3 times when no connections are present.

### ISSUE THREAD

**Issue by hunterSThompson** [sporritt/jsPlumb#523]
Fiddle: https://jsfiddle.net/hgraham92/tzqsgh7c/

Very basic setup. Using the instance level event handler jsPlumbInst.bind('endpointDblClick' function() { ... }); does't trigger at all, nor does 'endpointclick'.  Binding "click" triggers 3 times (even when there are no connections).

The endpoint instance events seem to work... but they also trigger 3 times for a single click.

**Comment by hunterSThompson** [comment]
Also:  Seeing this in Chrome Version 50.0.2661.102 m

**Comment by sporritt** [comment]
in development i see `click` being fired for a click on an endpoint, and no `endpointClick`. This explains one of the alerts you see but not all three. i'm looking into it.

incidentally if all the events were firing properly you would never see the `endpointDblClick` fire in that fiddle, since the alert that pops up after `endpointClick` would prevent you from ever catching the double click event.

**Comment by sporritt** [comment]
..ok i know what causes the 3 clicks, and why it started with recent versions.  Mottle, the underlying event library, had always had a small deficiency with delegated events, which required multiple selectors for binding. jsPlumb binds to this selector, for example, for endpoints:

`.jsplumb-endpoint, .jsplumb-endpoint > *, .jsplumb-endpoint svg *`

after the new version of Mottle was introduced this was no longer necessary. The selector can (should) now be:

`.jsplumb-endpoint`

I'll get this into a fix and release 2.1.2 shortly.  Also need to test overlays and connectors to make sure they dont suffer from the same problem.

As for `endpointClick`...seems every component just fires `click` through jsPlumb now. This of course does not agree with the documentation. Do you find a separate `endpointClick` registration to be useful?

**Comment by sporritt** [comment]
all fixed in 2.1.2, released today.
