### ISSUE TITLE
Dragging connection (SVG)

### ISSUE THREAD

**Issue by lconer** [sporritt/jsPlumb#524]
I would like to assign dragging option to connection (arrow between endpoints/elements).

When passed SVG canvas as a element into draggable function, dragging event do not return values inside details.pos object, and connection remains in this same place, dragging event is fired.

`Object {el: svg#jsPlumb_2_8, pos: Array[2], e: MouseEvent, drag: Drag}
drag
:
Drag
e
:
MouseEvent
el
:
svg#jsPlumb_2_8
pos
:
Array[2]
0
:
NaN
1
:
NaN
length
:
2
__proto__
:
Array[0]
__proto__
:
Object`

**Comment by sporritt** [comment]
this is not a good idea. the SVG elements are under jsPlumb's control. what exactly do you want to do this for?

**Comment by lconer** [comment]
Thanks for your response.

I've wanted to move connection with connected elements
I've done that by grouping elements and move them together with connection between them.

**Comment by sporritt** [comment]
you know you can drag more than one thing at a time in jsPlumb, right? You can use the `addToDragSelection(element)` method on an instance of jsPlumb. Then when you drag any element, all of the elements in the drag selection are dragged, too, and all of their connections are repainted as necessary.

https://jsplumbtoolkit.com/community/doc/dragging.html#multiple

**Comment by lconer** [comment]
I know, I found this in documentation.
Thanks

**Comment by chj-damon** [comment]
is it possible to drag a svg element using jsPlumb? I couldn't find any document about this.
