### ISSUE TITLE
Update npm package to version 2.1.2

### ISSUE THREAD

**Issue by uneart** [sporritt/jsPlumb#526]
The npm package is still on version 2.0.7. Could you please update that to the latest release?

**Comment by sporritt** [comment]
i think you mean the bower version?  package.json was showing 2.1.2, but bower.json had 2.0.7.  fixing this in 2.1.3, releasing a little later today.

**Comment by uneart** [comment]
No in fact I meant npm. The package.json was already 2.1.2 but for some reason there was still 2.0.7 on npmjs.com. Now it is fixed both on npm and Bower, thank you! 👍
