### ISSUE TITLE
Connectors of children disappear on GroupCollapse

### ISSUE THREAD

**Issue by markusdittrich** [sporritt/jsPlumb#530]
Suppose this fiddle: [https://jsfiddle.net/MarkusDittrich/Lrobpr9b/](https://jsfiddle.net/MarkusDittrich/Lrobpr9b/)

If the Elements get connected to each other _before_ being added to their groups, their connectors will disappear upon collapsing the group (they won't be "proxied").

If the Elements get connected after being added to the group, everything is fine: [https://jsfiddle.net/MarkusDittrich/c32a0cyx/1/](https://jsfiddle.net/MarkusDittrich/c32a0cyx/1/) 

Is this a bug, or am I missing something?

**Comment by sporritt** [comment]
probably a bug. i'll look into it.

**Comment by markusdittrich** [comment]
Another bug that could to be connected to this:
If you drag element 2.1 around (within the boundaries of the group), then delete the group and afterwards click on element 2.1 the element gets deleted (while the endpoints and connectors stay intact). 
This doesn't happen if you trigger the "revert-behaviour" by trying to drop the element outside of the group. 

[https://jsfiddle.net/MarkusDittrich/Lrobpr9b/](https://jsfiddle.net/MarkusDittrich/Lrobpr9b/)

**Comment by sporritt** [comment]
the main problem is fixed.  if the other problem persists please open a separate ticket.

**Comment by sporritt** [comment]
(in 2.1.3 it is fixed)

**Comment by markusdittrich** [comment]
Unfortunately there's still a minor issue with this in 2.1.3. Although the connectors are now proxied the behaviour doesn't seem to be entirely correct: https://jsfiddle.net/MarkusDittrich/c32a0cyx/2/

If I close "group 1", two connectors will be proxied, instead of one.

**Comment by sporritt** [comment]
hmm yeah i see this, but i can't reproduce it in a unit test for some reason.

**Comment by sporritt** [comment]
..and also if i change the jsplumb demo to connect everything to 1.1 first then i only get one proxy on collapse.
