### ISSUE TITLE
maybe draggable options should extend the default options rather than override them

### ISSUE THREAD

**Issue by HQidea** [sporritt/jsPlumb#535]
https://github.com/sporritt/jsPlumb/blob/master/src/jsPlumb.js#L740

**Comment by sporritt** [comment]
yes maybe, but a change like this is risky for backwards compatibility reasons. to be done safely it'd be best to make them not extend by default, and to leave the behaviour as it is, but add a flag that allows the user to specify to extend. This then adds to the complexity of the API. For that reason I think I'd prefer to leave the behaviour as it is.
