### ISSUE TITLE
Creating multiple anchors at the same time

### ISSUE THREAD

**Issue by przeqpiciel** [sporritt/jsPlumb#538]
Im trying to create multiple anchors at the same time. I readed documentary and i found jsPlumb.addEndpoint() method. But when i added array of position that only first position is added.

https://jsfiddle.net/g4btqn68/2/

**Comment by Helen1987** [comment]
As I know, it's not possible to add several endpoints at once. You have to add them by one in a loop. But I need this feature. I hope it will help with my performance issue.

**Comment by przeqpiciel** [comment]
Hi, thank you for respond. I fight with that problem for few last days and I found another function jsPlumb.addEndpoints() which is able to adds few endpoint at the same time. But it still is not satisfaying me.

**Comment by sporritt** [comment]
`addEndpoints` adds several at once.  I am closing this; if you think there is still an issue please expand on what "it still is not satisfying me" means.  thanks.
