### ISSUE TITLE
connection within hidden details element misbehaves

### ISSUE THREAD

**Issue by droundy** [sporritt/jsPlumb#540]
I am experiencing a misbehavior when creating connections to elements that are inside an HTML5 details element.  When that element is not open, the connection goes to the top-left corner of the page.  I would prefer to have the connection transfer to the parent (the closed details element), or if not that then to completely disappear.

I am observing this with Chrome.

**Comment by sporritt** [comment]
could i trouble you for a jsfiddle or something?

**Comment by droundy** [comment]
If you can give me a simple working example using jsPlumb, I could stick one element in a details element.  I'm not using jsPlumb any longer, and after half an hour have given up on getting it to draw anything with or without a details element.
