### ISSUE TITLE
Link to download for Archive version of Jsplumb

### ISSUE THREAD

**Issue by takaobaltazar** [sporritt/jsPlumb#544]
Hi everyone,

Is there anyone have a lower version of jsplumb? specifically 1.7.10 or 2.0.0 ? or link ? I've already tried searching over the net, but it seems that it only gives me the latest version of jsplumb.

Thank you.

**Comment by sporritt** [comment]
you can checkout the tag from github and get it from the `dist` directory.

**Comment by takaobaltazar** [comment]
Thank you so much. It saves my time. Sorry for this dumb question anyway.
