### ISSUE TITLE
Website Unavailable

### ISSUE THREAD

**Issue by shadowcodex** [sporritt/jsPlumb#546]
Trying to view this project, and demos. But not of the websites are responding.

**Comment by shadowcodex** [comment]
Tested at pingdom to verify, and yes it is unaccessable. https://tools.pingdom.com/#!/cMgcuV/http://jsplumbtoolkit.com/

**Comment by sporritt** [comment]
Amazon reported "degradation of the hardware" last night and told us the box was "probably inaccessible". Bringing up a new on today.

**Comment by sporritt** [comment]
up now.
