### ISSUE TITLE
Conflict between Magnetize and Hierarchical layout

### ISSUE THREAD

**Issue by Lavaei** [sporritt/jsPlumb#548]
> The below problem only occurs when we have more than one root nodes in the diagram.

`Magnetize` works well with `Absolute` layout. But when i change layout to something else (for example `Hierarchical`) get this message on firebug:

> jsPlumb: fire failed for event dataLoadEnd : TypeError: b is undefined

Above exception has occurred in line 2720 of `jsPlumb-2.1.5.js`

I have used your flowchart-builder example and just change the layout`s type and enable `Magnetize`.

**Comment by sporritt** [comment]
please use the support email address for Toolkit edition issues.
