### ISSUE TITLE
Question: Avoid connecotrs overlapping elements

### ISSUE THREAD

**Issue by Manuel83** [sporritt/jsPlumb#550]
How can I avoid that connectors overlap the elements. I have two elements in a row and the connector should go around the element. Is that possible?

http://fiddle.jshell.net/wGjDm/565/

**Comment by sporritt** [comment]
no, it's not possible currently.

**Comment by Manuel83** [comment]
Thanks for the fast response

**Comment by sporritt** [comment]
no problem. editable connectors are vaguely on the roadmap for this year, but that's editable by user intervention - not connectors that auto route around nodes.

**Comment by Manuel83** [comment]
Do you mean by editable to drag and drop the connectoin to the desired position? That would be fantastic and absolutely perfect.

I'm developing an open source brewing software and I like to display the kettle setup including the pipeline system. https://github.com/Manuel83/craftbeerpi

**Comment by sporritt** [comment]
yes, for flowchart editors you'll be able to drag segments, and for bezier/state machine connectors you'll be able to drag control points.

**Comment by sporritt** [comment]
(your brewing software looks pretty cool!)

**Comment by Manuel83** [comment]
Is there any update on this? I really looking forward to this feature.

**Comment by sporritt** [comment]
nope. well actually yes, it looks like when we do add it it will be in the toolkit edition, not the community edition. but still no definite time in mind.
