### ISSUE TITLE
Incorrect Endpoint position when canvas has relative position

### ISSUE THREAD

**Issue by raygig** [sporritt/jsPlumb#552]
I have jsPlumb drawing in a canvas that has position set to relative. This is similar to the statemachine example found on https://jsplumbtoolkit.com/community/demo/statemachine/index.html

Notice when you try to make a connection the endpoint in the top right corner. 

![image](https://cloud.githubusercontent.com/assets/1569098/18149001/560cd8e4-6fab-11e6-8a06-09668553eebc.png)

Is this a bug and is there a fix?

**Comment by sporritt** [comment]
can you elaborate on what you mean "a canvas that has position set to relative" ?

**Comment by sporritt** [comment]
actually dont worry about it; i can reproduce this in the state machine demo in dev.

**Comment by sporritt** [comment]
fixed in 2.1.6 dev branch. 2.1.6 will be released very soon. maybe even tonight.

**Comment by sporritt** [comment]
2.1.6 released.

**Comment by raygig** [comment]
Thank you for this fix!

**Comment by sporritt** [comment]
no problem. get 2.1.7 though. there was another issue in 2.1.6 that wasn't closed off properly.
