### ISSUE TITLE
Connectors broke if we drop node in group v2.1.5 latest Chrome

### ISSUE THREAD

**Issue by Ch0bits** [sporritt/jsPlumb#554]
There is a good demonstration of this issue in an official demo.
https://jsplumbtoolkit.com/community/demo/groups/index.html
Just slightly move node 2.1 and you will see how connections broke.
Screenshot before
![2016-09-05_01-13-08](https://cloud.githubusercontent.com/assets/739639/18234228/23883072-7306-11e6-890b-ab98f545adec.png)
Screenshot after
![2016-09-05_01-13-24](https://cloud.githubusercontent.com/assets/739639/18234229/2c0edb42-7306-11e6-8280-356817fc1532.png)

It was broken exactly in v2.1.5 because in v2.1.4 it works well.

**Comment by sporritt** [comment]
this is fixed in the 2.1.6 dev branch. 2.1.6 should be released in the next day or two.

**Comment by sporritt** [comment]
2.1.6 released.
