### ISSUE TITLE
Very long connectors get cut off

### ISSUE THREAD

**Issue by NielR** [sporritt/jsPlumb#556]
Connectors which are longer than the widht of the screen seem to get cut off.
This mostly seems to impact horizontal connectors or connectors with long horizontal parts at least.
When I tested with a long, purely vertical connector, no cutting off occured.

Putting the elements closer together is unfortunately not an option for me, as this piece of the project is a fairly massive decision tree where the formatting of all of the elements can put some of them a good distance apart.

Screengif included to illustrate:
![long-connectors-cut-off](https://cloud.githubusercontent.com/assets/2423125/18362517/493f4028-7606-11e6-9931-a9437771232f.gif)

(jsPlumb v2.1.7)

**Comment by sporritt** [comment]
Can you provide a jsfiddle?

**Comment by NielR** [comment]
I think I have finally found the issue though. In between the thousands of lines of code, there was a line in an included css file from our company which set a css for svg with max-width: 100%, as I was suspecting all along. Just took me a long time to dig through the entire thing...
Overwriting this line seems to fix it.

**Comment by sporritt** [comment]
thanks for letting me know.
