### ISSUE TITLE
2.2.0 release

### ISSUE THREAD

**Issue by tisto** [sporritt/jsPlumb#560]
I was wondering if it would be possible to make a 2.2.0 release anytime soon. I'm using 2.2.0 since quite a while (because I need the webpack support) and it works like a charm.

@sporritt Thanks for sharing your awesome work!

**Comment by sporritt** [comment]
well it definitely helps to get feedback like that.  i've been holding off on it because i was planning on tying it to a new release of the Toolkit edition but maybe i should just push out 2.2.0 sooner rather than later.

**Comment by tisto** [comment]
@sporritt A 2.2.0 release soon would be awesome. Please let me know if there is anything I can do to help!

**Comment by 4leem** [comment]
@sporritt Does the 2.2.0 work well with WebComponents.js as well ?

**Comment by sporritt** [comment]
@tisto i've just released 2.2.0, and published it to npm.

@4leem i dont know, i haven't used WebComponents.js.  Have you tried it since you posted on here?

**Comment by tisto** [comment]
@sporritt awesome! thanks a lot!
