### ISSUE TITLE
SVG width and height issue

### ISSUE THREAD

**Issue by flogo1982** [sporritt/jsPlumb#563]
I have a strange issue with Windows and Chrome book on Chrome browser:

![image](https://cloud.githubusercontent.com/assets/4402620/18896156/92b61918-84dc-11e6-9aaa-1be0af18119b.png)

I don't have this problem on mac with the same Chrome version:

![image](https://cloud.githubusercontent.com/assets/4402620/18896179/c85a9b0c-84dc-11e6-9be0-e61f2ed69681.png)

It seems that the SVG element width and height are too small for the child path.

**Comment by sporritt** [comment]
can you provide any more information?  can you show the outline of the SVG element?

**Comment by flogo1982** [comment]
I found the problem. Some css svg selection was conflicting with jsPlumb:

`.container {
  svg {
     width: auto;
     height: auto;
  }
}`

I just commented the svg selector and it works.
