### ISSUE TITLE
repaintEverything() makes strange arrows

### ISSUE THREAD

**Issue by Laplandia** [sporritt/jsPlumb#93]
After upgrading from 1.4.1 to 1.5.2 I noticed that jsPlumb.repaintEverything() results in different anchors compared to initial connect call. I.e. anchor moves from bottom border to the left and connector crosses source node.

**Comment by hamza-soussou** [comment]
Hello,

I'm facing the same issue with 1.7.5. Will this issue be fixed in later version?

Thanks

**Comment by sporritt** [comment]
tested this against 1.7.6 and seems to be working

http://jsfiddle.net/ZZKKg/56/
